### ISSUE TITLE
Cannot connect securely to <server address>

### ISSUE THREAD

**Issue by beuker81** [owncloud/client#11621]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

When I try to login one of the two account I get the message: Cannot connect securely to <server address>

I have no issue with the Windows Desktop app or the iPhone app but the Mac app doesn't work.
Also the webpage has no problem. Valid SSL Cert. Using Let's Encrypt.

### Expected behavior

That the owncloud app just login.

### Steps to reproduce the issue

1. Open owncloud
2. Click on the account you want to login
3. Click on account and then login
4. Error message

### Screenshots

![Screenshot 2024-05-01 at 00 24 30](https://github.com/owncloud/client/assets/5682660/be39b9f7-953c-4973-98e8-7e90c1544b04)

### Client version number

ownCloud Mac Desktop app 5.2.1.13040

### Desktop environment (Linux only)

MAC OSX Ventura 13.6.6 (22G630)

### Server information

ownCloud server 10.14.0.3

**Comment by TheOneRing** [comment]
The dialog suggests that there is something wrong.
As it only happens on that device.. have you checked the certificate in the browser on that system?
Are you using some proxy software on that device, maybe installed by your employer?

**Comment by beuker81** [comment]
> The dialog suggests that there is something wrong. As it only happens on that device.. have you checked the certificate in the browser on that system? Are you using some proxy software on that device, maybe installed by your employer?

Yes I have checked in a browser if there is something wrong with the certificate and no issue's. Just as how it should look like. I don't use any proxy software on the laptop. It's my private laptop.

**Comment by TheOneRing** [comment]
Could you please upload some client logs with httplogging enabled (https://doc.owncloud.com/desktop/next/appendices/troubleshooting.html#log-files) to:
https://infinite.owncloud.com/s/asdDIpEeRmoiFzT
PW: 99^&VqTfy1r*

**Comment by beuker81** [comment]
> Could you please upload some client logs with httplogging enabled (https://doc.owncloud.com/desktop/next/appendices/troubleshooting.html#log-files) to: https://infinite.owncloud.com/s/asdDIpEeRmoiFzT PW: 99^&VqTfy1r*

Done

**Comment by Sky3RN** [comment]
> ### Pre-submission Checks
> 
>     * [x]  I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
> 
>     * [x]  I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.
> 
> 
> ### Describe the bug
> 
> When I try to login one of the two account I get the message: Cannot connect securely to
> 
> I have no issue with the Windows Desktop app or the iPhone app but the Mac app doesn't work. Also the webpage has no problem. Valid SSL Cert. Using Let's Encrypt.
> ### Expected behavior
> 
> That the owncloud app just login.
> ### Steps to reproduce the issue
> 
>     1. Open owncloud
> 
>     2. Click on the account you want to login
> 
>     3. Click on account and then login
> 
>     4. Error message
> 
> 
> ### Screenshots
> 
> ![Screenshot 2024-05-01 at 00 24 30](https://private-user-images.githubusercontent.com/5682660/326998437-bed2c273-c632-4f0f-a01c-8a8c58e85e0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MjkxMzIsIm5iZiI6MTcxNDcyODgzMiwicGF0aCI6Ii81NjgyNjYwLzMyNjk5ODQzNy1iZWQyYzI3My1jNjMyLTRmMGYtYTAxYy04YThjNThlODVlMGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDNUMDkzMzUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDBhNmZlYzkzZDQxNDg3OTZiZDliMzZmODFjMjJmMmY4NjY0YjY4MGY1OWJlOWJhZTdiZTc0YWI5NTE0N2MyOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1mA36P0c3y0H3ibpS75IEPqkiOOEiH3oa8z871VBSXc)
> ### Logs
> 
> _No response_
> ### Client version number
> 
> ownCloud Mac Desktop app 5.2.1.13040
> ### Desktop environment (Linux only)
> 
> MAC OSX Ventura 13.6.6 (22G630)
> ### Client package version and origin (Linux only)
> 
> _No response_
> ### Installation path (Windows only)
> 
> _No response_
> ### Server information
> 
> ownCloud server 10.14.0.3
> ### Additional context
> 
> _No response_

I have the exact same issue since a few weeks, it's getting on my nerves ! 
The same message with the same fingerprints etc..
![Capture du 2024-05-02 15-50-07](https://github.com/owncloud/client/assets/129675027/d63ebf62-ae85-4f03-ab74-646aebe41c3c)

**Comment by Sky3RN** [comment]
I have the exact same issue since a few weeks, it's getting on my nerves !
The same message with the same fingerprints etc..

![Capture du 2024-05-02 15-50-07](https://github.com/owncloud/client/assets/129675027/257a8746-3a8b-4dbf-899c-79e1ef6abe4f)

**Comment by TheOneRing** [comment]
With  `d41d8cd98f00b204e9800998ecf8427e` we have the fingerprint of null.
The error message we get in the log is: 
`Error: SSL handshake failed: The issuer certificate could not be found`

**Comment by TheOneRing** [comment]
Does the issue only occur when the application is started or randomly?
If you decline the dialog and try it again, does it behave the same?

**Comment by Sky3RN** [comment]
> > Does the issue only occur when the application is started or randomly? If you decline the dialog and try it again, does it behave the same?
> 
> When the application starts it presents the issue. Also when you try again to manually login it also shows. When I decline the dialog the user does not login and when I click on login again the same message shows.

Same behaviour here !

**Comment by TheOneRing** [comment]
> I have the exact same issue since a few weeks, it's getting on my nerves ! The same message with the same fingerprints etc..
> 
> ![Capture du 2024-05-02 15-50-07](https://private-user-images.githubusercontent.com/129675027/327715560-257a8746-3a8b-4dbf-899c-79e1ef6abe4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3NDI2NjYsIm5iZiI6MTcxNDc0MjM2NiwicGF0aCI6Ii8xMjk2NzUwMjcvMzI3NzE1NTYwLTI1N2E4NzQ2LTNhOGItNGRiZi04OTljLTc5ZTFlZjZhYmU0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwM1QxMzE5MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNjA3Njg3NzNjMGI4MWFlY2EzYjdlNzlhOTUxMDA2MTc0ZWFhMGUxYzkwYmJhYjBkN2M0NzU1OWU4MTVkYzcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PWdCaysZOG2Fs8YDtBXxMq6-0iS55Mqco5R7NgTcA3M)

That Linux with the AppImage/our packages/system packages?
Also what distro are you using?

**Comment by Sky3RN** [comment]
> > I have the exact same issue since a few weeks, it's getting on my nerves ! The same message with the same fingerprints etc..
> > ![Capture du 2024-05-02 15-50-07](https://private-user-images.githubusercontent.com/129675027/327715560-257a8746-3a8b-4dbf-899c-79e1ef6abe4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3NDI2NjYsIm5iZiI6MTcxNDc0MjM2NiwicGF0aCI6Ii8xMjk2NzUwMjcvMzI3NzE1NTYwLTI1N2E4NzQ2LTNhOGItNGRiZi04OTljLTc5ZTFlZjZhYmU0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwM1QxMzE5MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNjA3Njg3NzNjMGI4MWFlY2EzYjdlNzlhOTUxMDA2MTc0ZWFhMGUxYzkwYmJhYjBkN2M0NzU1OWU4MTVkYzcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PWdCaysZOG2Fs8YDtBXxMq6-0iS55Mqco5R7NgTcA3M)
> 
> That Linux with the AppImage/our packages/system packages? 

If I remember well, it's from the official OwnCloud repo, not the AppImage. 

![Capture du 2024-05-03 15-28-42](https://github.com/owncloud/client/assets/129675027/8a37ebcf-be92-4b04-834e-cb58925fffd3)

> Also what distro are you using?

Ubuntu 20.04

**Comment by beuker81** [comment]
I have remove the 5.2.1 version and installed the older version 5.1.2.

My issue is resolved. Seems like an issue in the 5.2.1 version. I haven't tested 5.2.0.

Maybe this helps?

**Comment by Sky3RN** [comment]
> I have remove the 5.2.1 version and installed the older version 5.1.2.
> 
> My issue is resolved. Seems like an issue in the 5.2.1 version. I haven't tested 5.2.0.
> 
> Maybe this helps?

I gotta try this ! 

I'd like to keep my ownCloud package from the official repo, because I like the simplicity of updating in command line. 

Is there anyway to downgrade from **_sudo apt_** ?

**Comment by beuker81** [comment]
> > I have remove the 5.2.1 version and installed the older version 5.1.2.
> > My issue is resolved. Seems like an issue in the 5.2.1 version. I haven't tested 5.2.0.
> > Maybe this helps?
> 
> I gotta try this !
> 
> I'd like to keep my ownCloud package from the official repo, because I like the simplicity of updating in command line.
> 
> Is there anyway to downgrade from **_sudo apt_** ?

What you can do is: sudo apt-get install <package-name>=<package-version-number>

The version you need you can find here: https://download.owncloud.com/desktop/ownCloud/stable/5.1/linux/

Or search it with apt.

**Comment by Sky3RN** [comment]
> > > I have remove the 5.2.1 version and installed the older version 5.1.2.
> > > My issue is resolved. Seems like an issue in the 5.2.1 version. I haven't tested 5.2.0.
> > > Maybe this helps?
> > 
> > 
> > I gotta try this !
> > I'd like to keep my ownCloud package from the official repo, because I like the simplicity of updating in command line.
> > Is there anyway to downgrade from **_sudo apt_** ?
> 
> What you can do is: sudo apt-get install =
> 
> The version you need you can find here: https://download.owncloud.com/desktop/ownCloud/stable/5.1/linux/
> 
> Or search it with apt.

Thanks, just found it after writing my post ! 

Unfortunately for me this didn't solve my issue. I've tried the 5.1.2.12600 and 5.2.0.12726 !

What's the exact build you tried ?

**Comment by beuker81** [comment]
> What's the exact build you tried ?

5.1.2.12600

I think even before I updated I had a 5.0 version running. On a Mac you need to complete remove the client before using an older version. Seems to be a bug from many years ago.

**Comment by TheOneRing** [comment]
Downgrading is not supported and downgrading to a version with known issues is not recommended at all!!

**Comment by Sky3RN** [comment]
> On a Mac you need to complete remove the client before using an older version. Seems to be a bug from many years ago.

Tried to uninstall the client too here on Linux to install the 5.1.2 but still the same issue. :(

**Comment by TheOneRing** [comment]
Could you try updating back to 5.2.1 to validate that it's really the version?

For testing you could also try our coinstallable nightly 
https://download.owncloud.com/desktop/testpilotcloud/daily/6.0/

It will use a separate profile.

**Comment by beuker81** [comment]
> Could you try updating back to 5.2.1 to validate that it's really the version?

Ok reinstalling 5.2.1 didn't fix it but deleting 5.2.1 and installing 5.1.2 and now updating to 5.2.1 it still seems to work. Let me test it out for a couple of days. Maybe something in the profile/settings?

**Comment by TheOneRing** [comment]
Could affected users check their settings https://doc.owncloud.com/desktop/next/advanced_usage/configuration_file.html for a CaCertificates key?
If you find such a key could you please upload your settings to the above url?

**Comment by Sky3RN** [comment]
> Could affected users check their settings https://doc.owncloud.com/desktop/next/advanced_usage/configuration_file.html for a CaCertificates key? If you find such a key could you please upload your settings to the above url?

I won't be able to do this before Monday because I'm not home for the whole week-end, but I'll let you know as soon as possible ! 
For the moment I can only access to SSH to my computer to check the config file, and yes, there is a CaCertificate key in the owncloud.cfg ! 

> For testing you could also try our coinstallable nightly
> https://download.owncloud.com/desktop/testpilotcloud/daily/6.0/ 

I'll try on Monday, what do I need to do ? Simply install this version and run it ? 
Will it use my config file or generate a new one ? 
Maybe the issue might come from my config file ? (I have more than 1 To of files to sync so I hate reinitializing the config file etc.. 😄)

**Comment by Sky3RN** [comment]
Here's something interesting : I deleted the CaCertificate line from the .cfg file and the error message has gone ! :+1: 
So that's the solution, I guess an old key was in the file and ownCloud was looking for it. 

By the way, I also tried to install the testpilot 6.0 version but couldn't do it. 
![Capture du 2024-05-06 09-42-16](https://github.com/owncloud/client/assets/129675027/28d3531b-3bd2-4f12-9228-f11c917fc04b)

**Comment by beuker81** [comment]
I don't have any problems when I did a clean install of the client so it seems that my issue is also a CaCert in the config file.
I checked old configs from my time machine backup and those have the CaCertificates key part in it. In the new config this does not exist so it seems this resolved the issue. Thanks!
