### ISSUE TITLE
Bad Gateway or timeouts possibly related by mirall-activity (see core#14187)

### ISSUE THREAD

**Issue by Xsysstar** [owncloud/client#2913]
Dear sirs/madams,

Would you kindly help investigate https://github.com/owncloud/core/issues/14187#issuecomment-76013986? User @StormCh indicates a possible relation between mirall and server errors that started occurring since upgrading the ownCloud server to version 8. I can confirm that the client has some odd behaviors at the very least.

It would also be helpful if you could bring some core-developers to join that discussion. We (the users) need instructions from developers to trace and pinpoint the problem, but we can't seem to get in touch with them.

**Comment by ogoffart** [comment]
What are the call that are too frequent?  Do ou have an apache logs showing the call from the client?

**Comment by Xsysstar** [comment]
I do not know if there are calls being made too frequent. But nginx (not apache) shows this:
```
130.89.161.145 - wrcdrijfhout [03/Mar/2015:14:32:00 +0100] "PROPFIND /remote.php/webdav/Hobby HTTP/1.1" 207 451 "-" "Mozilla/5.0 (Windows) mirall/1.8.0"
130.89.161.145 - wrcdrijfhout [03/Mar/2015:14:32:00 +0100] "PROPFIND /remote.php/webdav/Library HTTP/1.1" 207 452 "-" "Mozilla/5.0 (Windows) mirall/1.8.0"
130.89.161.145 - wrcdrijfhout [03/Mar/2015:14:32:00 +0100] "PROPFIND /remote.php/webdav/Pictures HTTP/1.1" 207 454 "-" "Mozilla/5.0 (Windows) mirall/1.8.0"
130.89.161.145 - wrcdrijfhout [03/Mar/2015:14:32:00 +0100] "PROPFIND /remote.php/webdav/Klusjes HTTP/1.1" 207 448 "-" "Mozilla/5.0 (Windows) mirall/1.8.0"
130.89.161.145 - wrcdrijfhout [03/Mar/2015:14:32:00 +0100] "PROPFIND /remote.php/webdav/Music HTTP/1.1" 207 452 "-" "Mozilla/5.0 (Windows) mirall/1.8.0"
130.89.161.145 - wrcdrijfhout [03/Mar/2015:14:32:01 +0100] "PROPFIND /remote.php/webdav/Studie HTTP/1.1" 207 452 "-" "Mozilla/5.0 (Windows) mirall/1.8.0"
130.89.161.145 - wrcdrijfhout [03/Mar/2015:14:32:01 +0100] "PROPFIND /remote.php/webdav/Notes HTTP/1.1" 207 445 "-" "Mozilla/5.0 (Windows) mirall/1.8.0"
130.89.161.145 - wrcdrijfhout [03/Mar/2015:14:32:01 +0100] "PROPFIND /remote.php/webdav/Persoonlijk HTTP/1.1" 207 456 "-" "Mozilla/5.0 (Windows) mirall/1.8.0"
130.89.161.145 - wrcdrijfhout [03/Mar/2015:14:32:01 +0100] "PROPFIND /remote.php/webdav/Saved%20Games HTTP/1.1" 207 460 "-" "Mozilla/5.0 (Windows) mirall/1.8.0"
130.89.161.145 - wrcdrijfhout [03/Mar/2015:14:32:01 +0100] "PROPFIND /remote.php/webdav/Videos HTTP/1.1" 207 449 "-" "Mozilla/5.0 (Windows) mirall/1.8.0"
130.89.161.145 - wrcdrijfhout [03/Mar/2015:14:32:01 +0100] "PROPFIND /remote.php/webdav/Werk HTTP/1.1" 207 449 "-" "Mozilla/5.0 (Windows) mirall/1.8.0"
130.89.161.145 - wrcdrijfhout [03/Mar/2015:14:32:01 +0100] "PROPFIND /remote.php/webdav/Sites HTTP/1.1" 207 444 "-" "Mozilla/5.0 (Windows) mirall/1.8.0"
130.89.161.145 - wrcdrijfhout [03/Mar/2015:14:32:09 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 523 "-" "Mozilla/5.0 (Windows) mirall/1.8.0"
130.89.161.145 - wrcdrijfhout [03/Mar/2015:14:37:23 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 504 191 "-" "Mozilla/5.0 (Windows) mirall/1.8.0"
130.89.161.145 - wrcdrijfhout [03/Mar/2015:14:37:30 +0100] "PROPFIND /remote.php/webdav/Hobby HTTP/1.1" 499 0 "-" "Mozilla/5.0 (Windows) mirall/1.8.0"
130.89.161.145 - wrcdrijfhout [03/Mar/2015:14:37:39 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 499 0 "-" "Mozilla/5.0 (Windows) mirall/1.8.0"
130.89.161.145 - wrcdrijfhout [03/Mar/2015:14:37:55 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 499 0 "-" "Mozilla/5.0 (Windows) mirall/1.8.0"
130.89.161.145 - wrcdrijfhout [03/Mar/2015:14:38:27 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 499 0 "-" "Mozilla/5.0 (Windows) mirall/1.8.0"
130.89.161.145 - wrcdrijfhout [03/Mar/2015:14:38:59 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 499 0 "-" "Mozilla/5.0 (Windows) mirall/1.8.0"
```
Notice that codes 207 suddenly change into 504 (Gateway time-out) and then into 499 (nginx-specific, but it should [apparently be interpreted as 504](http://stackoverflow.com/questions/12973304/nginx-an-d-499-error-codes)). My webbrowser (Firefox) reports 504 too.

Mirall reports "De verstrekte inloggegevens zijn niet juist" (The supplied log-in credentials are invalid), which is untrue. The mirall log reports erroneous entries: "Operation canceled" twice and then "Connection time-out", all pertaining to the same file.

**Comment by ogoffart** [comment]
The wronly reported error about crendentials invalid have been fixed.

I see that you have many server configured (at least 12)
The client polls the 12 folders every 30 seconds  (that's the 12 calls at 14:32) + one call for the quota.

then one see that it takes several minutes between the last call at 14:32:09  and the next one.  That's not normal, there should be many call every 30 seconds.  
Perhaps that's because the calls are so long that they are queueud.
Anyway, this of course results in timeouts in the client.

It just looks as if the owncloud server is too slow, or does not answer within 5 minutes for one of the call

**Comment by Xsysstar** [comment]
The server never recovers from the situation until I `service php5-fpm restart`. Sometimes php-fpm processes actually seem to have crashed.

The 64-bit Ubuntu server on which ownCloud runs has an Core i5-2300 CPU @ 2.80Ghz (4 physical cores) and 8GB of RAM. When ownCloud works, the web interface is quite speedy. I do not think hardware is a problem.

Following your suggestion that queued requests could cause timeouts (and the hypothesis that timeouts cause mayhem that cannot be recovered from), I have just modified `/etc/php5/fpm/pool.d/www.conf` as follows:
```
pm.max_children = 16
```
This should be sufficient to prevent any queuing.

I also want to show the slow-log:
```
[03-Mar-2015 13:04:25]  [pool www] pid 11827
script_filename = /var/www/owncloud/index.php
[0x00007f72126c1470] execute() /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91
[0x00007f72126c1320] execute() /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Statement.php:165
[0x00007f72126c11e0] execute() /var/www/owncloud/lib/private/db/statementwrapper.php:63
[0x00007f72126c10b0] execute() /var/www/owncloud/lib/private/db.php:141
[0x00007f72126c0f68] executeAudited() /var/www/owncloud/lib/private/files/cache/cache.php:271
[0x00007f72126c0da0] update() /var/www/owncloud/lib/private/files/cache/cache.php:213
[0x00007f72126c0c68] put() /var/www/owncloud/lib/private/files/cache/scanner.php:198
[0x00007f72126c0a50] updateCache() /var/www/owncloud/lib/private/files/cache/scanner.php:305
[0x00007f72126c0810] scanChildren() /var/www/owncloud/lib/private/files/cache/scanner.php:298
[0x00007f72126c06a0] scanChildren() /var/www/owncloud/lib/private/files/cache/scanner.php:216
[0x00007f72126c0560] scan() /var/www/owncloud/lib/private/files/cache/scanner.php:332
[0x00007f72126c03f8] backgroundScan() /var/www/owncloud/lib/private/files/utils/scanner.php:108
[0x00007f72126c0288] backgroundScan() /var/www/owncloud/apps/files/ajax/scan.php:29
[0x00007f72126c0178] +++ dump failed

[03-Mar-2015 14:32:47]  [pool www] pid 29620
script_filename = /var/www/owncloud/remote.php
[0x00007f847a4db048] apc_store() /var/www/owncloud/lib/private/memcache/apc.php:21
[0x00007f847a4daf08] set() /var/www/owncloud/lib/autoloader.php:109
[0x00007fffbcbf10f0] load() unknown:0
[0x00007fffbcbf1440] spl_autoload_call() unknown:0
[0x00007f847a4dacb8] init() /var/www/owncloud/lib/base.php:519
[0x00007f847a4dabb0] init() /var/www/owncloud/lib/base.php:1007
[0x00007f847a4daa70] +++ dump failed

[03-Mar-2015 14:32:47]  [pool www] pid 29375
script_filename = /var/www/owncloud/remote.php
[0x00007f847a4db050] apc_store() /var/www/owncloud/lib/private/memcache/apc.php:21
[0x00007f847a4daf10] set() /var/www/owncloud/lib/autoloader.php:109
[0x00007fffbcbf10f0] load() unknown:0
[0x00007fffbcbf1440] spl_autoload_call() unknown:0
[0x00007f847a4dacc0] init() /var/www/owncloud/lib/base.php:519
[0x00007f847a4dabb8] init() /var/www/owncloud/lib/base.php:1007
[0x00007f847a4daa78] +++ dump failed

[03-Mar-2015 14:32:54]  [pool www] pid 3032
script_filename = /var/www/owncloud/remote.php
[0x00007f847a4db048] apc_store() /var/www/owncloud/lib/private/memcache/apc.php:21
[0x00007f847a4daf08] set() /var/www/owncloud/lib/autoloader.php:109
[0x00007fffbcbf10f0] load() unknown:0
[0x00007fffbcbf1440] spl_autoload_call() unknown:0
[0x00007f847a4dacb8] init() /var/www/owncloud/lib/base.php:519
[0x00007f847a4dabb0] init() /var/www/owncloud/lib/base.php:1007
[0x00007f847a4daa70] +++ dump failed

[03-Mar-2015 14:32:54]  [pool www] pid 3058
script_filename = /var/www/owncloud/remote.php
[0x00007f847a4db058] apc_store() /var/www/owncloud/lib/private/memcache/apc.php:21
[0x00007f847a4daf18] set() /var/www/owncloud/lib/autoloader.php:109
[0x00007fffbcbf10f0] load() unknown:0
[0x00007fffbcbf1440] spl_autoload_call() unknown:0
[0x00007f847a4dacc8] init() /var/www/owncloud/lib/base.php:519
[0x00007f847a4dabc0] init() /var/www/owncloud/lib/base.php:1007
[0x00007f847a4daa80] +++ dump failed

[03-Mar-2015 14:37:54]  [pool www] pid 10394
script_filename = /var/www/owncloud/remote.php
[0x00007f847a4db048] apc_store() /var/www/owncloud/lib/private/memcache/apc.php:21
[0x00007f847a4daf08] set() /var/www/owncloud/lib/autoloader.php:109
[0x00007fffbcbf10f0] load() unknown:0
[0x00007fffbcbf1440] spl_autoload_call() unknown:0
[0x00007f847a4dacb8] init() /var/www/owncloud/lib/base.php:519
[0x00007f847a4dabb0] init() /var/www/owncloud/lib/base.php:1007
[0x00007f847a4daa70] +++ dump failed

[03-Mar-2015 14:37:54]  [pool www] pid 10395
script_filename = /var/www/owncloud/remote.php
[0x00007f847a4db050] apc_store() /var/www/owncloud/lib/private/memcache/apc.php:21
[0x00007f847a4daf10] set() /var/www/owncloud/lib/autoloader.php:109
[0x00007fffbcbf10f0] load() unknown:0
[0x00007fffbcbf1440] spl_autoload_call() unknown:0
[0x00007f847a4dacc0] init() /var/www/owncloud/lib/base.php:519
[0x00007f847a4dabb8] init() /var/www/owncloud/lib/base.php:1007
[0x00007f847a4daa78] +++ dump failed

[03-Mar-2015 14:38:00]  [pool www] pid 10534
script_filename = /var/www/owncloud/remote.php
[0x00007f847a4db048] apc_store() /var/www/owncloud/lib/private/memcache/apc.php:21
[0x00007f847a4daf08] set() /var/www/owncloud/lib/autoloader.php:109
[0x00007fffbcbf10f0] load() unknown:0
[0x00007fffbcbf1440] spl_autoload_call() unknown:0
[0x00007f847a4dacb8] init() /var/www/owncloud/lib/base.php:519
[0x00007f847a4dabb0] init() /var/www/owncloud/lib/base.php:1007
[0x00007f847a4daa70] +++ dump failed

[03-Mar-2015 14:38:00]  [pool www] pid 10535
script_filename = /var/www/owncloud/remote.php
[0x00007f847a4db050] apc_store() /var/www/owncloud/lib/private/memcache/apc.php:21
[0x00007f847a4daf10] set() /var/www/owncloud/lib/autoloader.php:109
[0x00007fffbcbf10f0] load() unknown:0
[0x00007fffbcbf1440] spl_autoload_call() unknown:0
[0x00007f847a4dacc0] init() /var/www/owncloud/lib/base.php:519
[0x00007f847a4dabb8] init() /var/www/owncloud/lib/base.php:1007
[0x00007f847a4daa78] +++ dump failed

[03-Mar-2015 14:42:54]  [pool www] pid 15527
script_filename = /var/www/owncloud/remote.php
[0x00007f847a4db048] apc_store() /var/www/owncloud/lib/private/memcache/apc.php:21
[0x00007f847a4daf08] set() /var/www/owncloud/lib/autoloader.php:109
[0x00007fffbcbf10f0] load() unknown:0
[0x00007fffbcbf1440] spl_autoload_call() unknown:0
[0x00007f847a4dacb8] init() /var/www/owncloud/lib/base.php:519
[0x00007f847a4dabb0] init() /var/www/owncloud/lib/base.php:1007
[0x00007f847a4daa70] +++ dump failed

[03-Mar-2015 14:42:54]  [pool www] pid 15528
script_filename = /var/www/owncloud/index.php
[0x00007f847a4db3a8] apc_store() /var/www/owncloud/lib/private/memcache/apc.php:21
[0x00007f847a4db268] set() /var/www/owncloud/lib/autoloader.php:109
[0x00007fffbcbf10f0] load() unknown:0
[0x00007fffbcbf1440] spl_autoload_call() unknown:0
[0x00007f847a4db018] init() /var/www/owncloud/lib/base.php:519
[0x00007f847a4daf10] init() /var/www/owncloud/lib/base.php:1007
[0x00007f847a4dae28] +++ dump failed

[03-Mar-2015 14:43:00]  [pool www] pid 15609
script_filename = /var/www/owncloud/remote.php
[0x00007f847a4db048] apc_store() /var/www/owncloud/lib/private/memcache/apc.php:21
[0x00007f847a4daf08] set() /var/www/owncloud/lib/autoloader.php:109
[0x00007fffbcbf10f0] load() unknown:0
[0x00007fffbcbf1440] spl_autoload_call() unknown:0
[0x00007f847a4dacb8] init() /var/www/owncloud/lib/base.php:519
[0x00007f847a4dabb0] init() /var/www/owncloud/lib/base.php:1007
[0x00007f847a4daa70] +++ dump failed

[03-Mar-2015 14:43:00]  [pool www] pid 15610
script_filename = /var/www/owncloud/remote.php
[0x00007f847a4db050] apc_store() /var/www/owncloud/lib/private/memcache/apc.php:21
[0x00007f847a4daf10] set() /var/www/owncloud/lib/autoloader.php:109
[0x00007fffbcbf10f0] load() unknown:0
[0x00007fffbcbf1440] spl_autoload_call() unknown:0
[0x00007f847a4dacc0] init() /var/www/owncloud/lib/base.php:519
[0x00007f847a4dabb8] init() /var/www/owncloud/lib/base.php:1007
[0x00007f847a4daa78] +++ dump failed
```
As you can see, the failing "update request batch" around 14:32 corresponds with hanging calls to `apc_store`. Does APC not play nice with queued or parallel requests, perhaps?

**Comment by dragotin** [comment]
@karlitschek @DeepDiver1975 pls. note this

**Comment by Xsysstar** [comment]
From the owncloud-log:
```
{"reqId":"a8897d741b8e46e727db8f3e1bc8ff81","remoteAddr":"46.166.188.228","app":"PHP","message":"apc_store(): GC cache entry 'ocfaed2607f1\/AutoloaderOCP\\Diagnostics\\IQueryLogger' was on gc-list for 3647 seconds at \/var\/www\/owncloud\/lib\/private\/memcache\/apc.php#21","level":3,"time":"2015-03-03T17:04:37+01:00"}
{"reqId":"a8897d741b8e46e727db8f3e1bc8ff81","remoteAddr":"46.166.188.228","app":"PHP","message":"apc_store(): GC cache entry 'ocfaed2607f1\/AutoloaderOCP\\IAppConfig' was on gc-list for 3647 seconds at \/var\/www\/owncloud\/lib\/private\/memcache\/apc.php#21","level":3,"time":"2015-03-03T17:04:37+01:00"}
{"reqId":"a8897d741b8e46e727db8f3e1bc8ff81","remoteAddr":"46.166.188.228","app":"PHP","message":"apc_store(): GC cache entry 'ocfaed2607f1\/AutoloaderOC\\Hooks\\Emitter' was on gc-list for 3647 seconds at \/var\/www\/owncloud\/lib\/private\/memcache\/apc.php#21","level":3,"time":"2015-03-03T17:04:37+01:00"}
{"reqId":"a8897d741b8e46e727db8f3e1bc8ff81","remoteAddr":"46.166.188.228","app":"PHP","message":"apc_store(): GC cache entry 'ocfaed2607f1\/AutoloaderOC\\Files\\Stream\\Close' was on gc-list for 3647 seconds at \/var\/www\/owncloud\/lib\/private\/memcache\/apc.php#21","level":3,"time":"2015-03-03T17:04:37+01:00"}
{"reqId":"a8897d741b8e46e727db8f3e1bc8ff81","remoteAddr":"46.166.188.228","app":"PHP","message":"apc_store(): GC cache entry 'ocfaed2607f1\/AutoloaderOC_Log' was on gc-list for 3647 seconds at \/var\/www\/owncloud\/lib\/private\/memcache\/apc.php#21","level":3,"time":"2015-03-03T17:04:37+01:00"}
{"reqId":"a8897d741b8e46e727db8f3e1bc8ff81","remoteAddr":"46.166.188.228","app":"PHP","message":"apc_store(): GC cache entry 'ocfaed2607f1\/AutoloaderOC\\Log\\ErrorHandler' was on gc-list for 3647 seconds at \/var\/www\/owncloud\/lib\/private\/memcache\/apc.php#21","level":3,"time":"2015-03-03T17:04:37+01:00"}
```
Meanwhile in `nginx/access.log`:
```
130.89.161.145 - wrcdrijfhout [03/Mar/2015:17:04:35 +0100] "PROPFIND /remote.php/webdav/Saved%20Games HTTP/1.1" 207 460 "-" "Mozilla/5.0 (Windows) mirall/1.8.0"
130.89.161.145 - wrcdrijfhout [03/Mar/2015:17:04:36 +0100] "PROPFIND /remote.php/webdav/Videos HTTP/1.1" 207 449 "-" "Mozilla/5.0 (Windows) mirall/1.8.0"
130.89.161.145 - wrcdrijfhout [03/Mar/2015:17:04:36 +0100] "PROPFIND /remote.php/webdav/Werk HTTP/1.1" 207 449 "-" "Mozilla/5.0 (Windows) mirall/1.8.0"
130.89.161.145 - wrcdrijfhout [03/Mar/2015:17:04:36 +0100] "PROPFIND /remote.php/webdav/Sites HTTP/1.1" 207 444 "-" "Mozilla/5.0 (Windows) mirall/1.8.0"
130.89.161.145 - wrcdrijfhout [03/Mar/2015:17:09:45 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 499 0 "-" "Mozilla/5.0 (Windows) mirall/1.8.0"
130.89.161.145 - wrcdrijfhout [03/Mar/2015:17:09:57 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 499 0 "-" "Mozilla/5.0 (Windows) mirall/1.8.0"
130.89.161.145 - wrcdrijfhout [03/Mar/2015:17:10:04 +0100] "PROPFIND /remote.php/webdav/Hobby HTTP/1.1" 499 0 "-" "Mozilla/5.0 (Windows) mirall/1.8.0"
130.89.161.145 - wrcdrijfhout [03/Mar/2015:17:10:29 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 499 0 "-" "Mozilla/5.0 (Windows) mirall/1.8.0"
130.89.161.145 - wrcdrijfhout [03/Mar/2015:17:11:01 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 499 0 "-" "Mozilla/5.0 (Windows) mirall/1.8.0"
130.89.161.145 - wrcdrijfhout [03/Mar/2015:17:11:33 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 499 0 "-" "Mozilla/5.0 (Windows) mirall/1.8.0"
130.89.161.145 - wrcdrijfhout [03/Mar/2015:17:14:45 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 499 0 "-" "Mozilla/5.0 (Windows) mirall/1.8.0"
130.89.161.145 - wrcdrijfhout [03/Mar/2015:17:14:57 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 499 0 "-" "Mozilla/5.0 (Windows) mirall/1.8.0"
130.89.161.145 - wrcdrijfhout [03/Mar/2015:17:15:04 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 499 0 "-" "Mozilla/5.0 (Windows) mirall/1.8.0"
130.89.161.145 - wrcdrijfhout [03/Mar/2015:17:15:29 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 499 0 "-" "Mozilla/5.0 (Windows) mirall/1.8.0"
130.89.161.145 - wrcdrijfhout [03/Mar/2015:17:16:01 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 499 0 "-" "Mozilla/5.0 (Windows) mirall/1.8.0"
130.89.161.145 - wrcdrijfhout [03/Mar/2015:17:16:33 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 499 0 "-" "Mozilla/5.0 (Windows) mirall/1.8.0"
```
And, in `nginx/error.log`, a series of entries like:
```
2015/03/03 17:17:57 [error] 5015#0: *54253 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 109.201.152.229, server: owncloud.imperamus.eu, request: "GET /status.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock", host: "owncloud.imperamus.eu"
```

**Comment by Xsysstar** [comment]
My attempt (shown below) failed; the problem persists and occurs repeatedly throughout the day.
> Following your suggestion that queued requests could cause timeouts (and the hypothesis that timeouts cause mayhem that cannot be recovered from), I have just modified /etc/php5/fpm/pool.d/www.conf as follows:
>
> ```
> pm.max_children = 16
> ```

I am wondering if ownCloud 8 (compared to 7) may simply cache more to memory than APC is permitted to use. It would explain the ungraceful failing of php5-fpm (OutOfMemory is difficult to deal with) and may explain the slow calls to `apc_store` (waiting for memory to free up). I reckon that any fpm-process that calls `apc_store` may cause out-of-memory to occur for the whole of fpm, which would explain why all workers fail and they can't be restarted by fpm either.

Do you know if ownCloud 8 caches more or caches differently, compared to 7? I suppose I'll have to investigate memory usage of APC later this week.

**Comment by dragotin** [comment]
I am closing this one as it is not client related. Please continue in the server repo if required. Thanks.
