### ISSUE TITLE
[1.8.1] An error occurred while opening a directory Connection closed

### ISSUE THREAD

**Issue by cdamken** [owncloud/client#3248]
### Architecture
Client windows 7 1.8.1
Server 6.0.6

The client stops and displays the error:
### Full log file:

S3-ownCloud\Shared\owncloud\support\github-issues\client\3248

@MorrisJobke 

00003171

**Comment by guruz** [comment]
btw, the ```OCC::SocketApi``` log entries are not related at all to the sync discovery.
What are the log lines from the csync/vio?

**Comment by cdamken** [comment]
Sorry, I copied the wrong line, but you can see the full logfile :smile:

**Comment by cdamken** [comment]
This is the line I think:
```
05-19 11:07:04:601 0x74e1f10 OCC::DiscoveryMainThread::singleDirectoryJobResultSlot: void OCC::DiscoveryMainThread::singleDirectoryJobResultSlot(const QList<OCC::FileStatPointer>&) Have 2 results for  "/Shared/Sync Clients/Desktop/xxxxx1.6.0"
```

**Comment by cdamken** [comment]
@guruz S3-ownCloud\Shared\owncloud\support\github-issues\client\3248

**Comment by guruz** [comment]
How reproducably do you get this issue?
I believe that 06c889630cb9834a5060286b2a2dac2c3bbbb881 could improve this.
Could you try with a recent nightly?

**Comment by guruz** [comment]
This is an updated ```Qt5Network.dll``` with a small patch that fixes this for me. Could you please test? It should match the DLLs shipped with 1.8.1

https://cloud.molkentin.net/index.php/s/LUPHW89fEBPZpTA

**Comment by TheOtterslider** [comment]
I think this may be my issue.  I was running the 1.8.1 client.  I'd get perhaps 3-12 files downloaded an an error (it varied but was always vague and I didn't see anything specific in the logs).  At first, I blamed my ISP at home or the ISP I connected to; however, I did some testing and switched that.  Today I decided to try the 1.7.1 client....I haven't experienced those errors since rolling back to 1.7.1.

I'm willing to help out, troubleshoot, send logs, etc... whatever you guys need/want.  Or, if you think it is another problem, I'll open a new ticket,

**Comment by guruz** [comment]
@TheOtterslider which client OS did you test on?

**Comment by TheOtterslider** [comment]
I experienced the issue (and resolution) with both the windows and mac clients.

When I talk about sync issues below, the client would sync anywhere from 3-12 (sometimes more) files then throw what appeared to be a random error (the error above was one of them, sometimes it was socket closed, sometimes it was host not found).  In all cases, the error was bogus, I think...for example, immediately after receiving the host not found error, I could open a browser and get to the ownCloud web interface.

Here's some more detail:
Upgraded server to 8.0.3
Got a new mac and installed 1.8.1.
Tried to download my content and had nothing but problems (the exact error displayed in the sync client varied, but this was one of them).
I had the problem regardless of how I connected (over the internet, over the LAN, using a hosts file entry to force the traffic on the lan)
At first, I thought it might have been an issue with the upgrade on the server side (I found a forum post talking about having "old" server files around) so I did a brand new install and moved my config file over.  Still had the issue both over the internet and lan.
I found some other posts talking about the problem perhaps being related to the ownCloud DB having incorrect sizes for files and the client barfing because the bytes received didn't jive with what the server was telling it to expect.  I rescanned the filesystem with the command line client.  Still had the issue over the internet and lan
I upgraded my windows computer to 1.8.1 before I left.  It developed sync issues.
I decided to move my server to another lan (I have 2 at home).  Still had issues syncing over the lan.

The last thing I had to do was do a brand new install, manually move the server files, and rebuild the database.  Before doing that step though, I thought I'd roll back clients (just because it was easier).

After rolling back both of them, I haven't had any of the sync errors.  I've synched 10s of GB over night and had no issues on either computer

**Comment by danimo** [comment]
@cdamken Please try http://download.owncloud.com/desktop/daily/ownCloud-1.8.2.5124-nightly20150529-setup.exe. It includes @guruz' fix and you should no longer see the "Connection Closed" error.

**Comment by Dianafg76** [comment]
I tested this issue in:
.- WINDOWS:
. DESKTOP: 1.8.2 (build 5139)
. SERVER: {"installed":"true","version":"6.0.6.1","versionstring":"6.0.6","edition":"enterprise"}

And everythig is OK, so I close the issue

**Comment by guruz** [comment]
@TheOtterslider the OS X nightly build version will have a fix for that problem from tomorrow morning.. :)
http://download.owncloud.com/desktop/daily/

**Comment by caratsch** [comment]
@guruz I tested it with the Windows sync client you provided in the other issue. I was not able to reproduce this again with this client. I think this is fixed now.

**Comment by guruz** [comment]
@caratsch Thanks. :) Also the low upload speed problem is fixed? (Did you try that one in a VM?)

**Comment by caratsch** [comment]
@guruz yes, performance is good now. No, I don't use a VM for testing. I have a Windows system where I test and run the client.

**Comment by dragotin** [comment]
Great! Thanks @guruz and @jturcotte and @ogoffart for chrunching this one. You rock!

**Comment by TheOtterslider** [comment]
I downloaded ownCloud-1.8.2.2404-nightly20150605.pkg (yes, I have a mac).  I don't get the connection closed message, but I'm still getting an error:  "An unknown error has occurred" when it is trying to set up the sync.

**Comment by guruz** [comment]
@TheOtterslider Then you'd need to run it via 
```
/Applications/owncloud.app/Contents/MacOS/owncloud --logfile -
```
And paste the relevant log parts here so we see what is going on

**Comment by TheOtterslider** [comment]
ok...I downloaded today's (6 June) nightly for the mac.  I still get the error.  Here's what I think are the relevant parts of the output:

Changes I made:
MY_OWNCLOUD_URL = the real proper path to my owncloud install
PATH_48Chars_UpperLowerLettersOnly_5Dirs_END = The path that it is trying to sync.  This path contains 48 total characters (including the /).  The name has only Upper and Lower letters.  It contains a total of 5 directories
USERNAME = My Username on my local machine
I'm willing to PM or email these to a member of the team if you want to verify or have a look.

-----
06-06 10:22:00:942 0x7fdbbe1e02f0 csync_ftw:  <= Closing walk for ownclouds://MY_OWNCLOUD_URL/remote.php/webdav/PATH_48Chars_UpperLowerLettersOnly_5Dirs_END/20090324 with read_from_db 0
06-06 10:22:00:942 0x7fdbbe1e02f0 csync_walker: directory: ownclouds://MY_OWNCLOUD_URL/remote.php/webdav/PATH_48Chars_UpperLowerLettersOnly_5Dirs_END/20090325 [file_id=02224021oc8e61b24903]
06-06 10:22:00:942 0x7fdbbe1e02f0 _csync_detect_update: file: PATH_48Chars_UpperLowerLettersOnly_5Dirs_END/20090325, instruction: INSTRUCTION_NEW <<=
06-06 10:22:00:942 0x7fdbbe1e02f0 csync_ftw: URI without fuzz for ownclouds://MY_OWNCLOUD_URL/remote.php/webdav/PATH_48Chars_UpperLowerLettersOnly_5Dirs_END/20090325 is "PATH_48Chars_UpperLowerLettersOnly_5Dirs_END/20090325"
06-06 10:22:00:942 0x7fdbbe1e02f0 OCC::DiscoveryJob::remote_vio_opendir_hook: static csync_vio_handle_t *OCC::DiscoveryJob::remote_vio_opendir_hook(const char *, void *) OCC::DiscoveryJob(0x7fdbbe24aa20) PATH_48Chars_UpperLowerLettersOnly_5Dirs_END/20090325 Calling into main thread...
06-06 10:22:00:942 0x7fdbbbc43890 OCC::AbstractNetworkJob::start: !!! OCC::LsColJob created for "https://MY_OWNCLOUD_URL" + "/PATH_48Chars_UpperLowerLettersOnly_5Dirs_END/20090325"
06-06 10:22:01:366 0x7fdbbbc588d0 unknown: QIODevice::write: device not open
06-06 10:22:01:366 0x7fdbbbc43890 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() 99 "Unknown error"
06-06 10:22:01:367 0x7fdbbbc43890 OCC::DiscoverySingleDirectoryJob::lsJobFinishedWithErrorSlot: void OCC::DiscoverySingleDirectoryJob::lsJobFinishedWithErrorSlot(QNetworkReply *) "Unknown error" 0 99
06-06 10:22:01:367 0x7fdbbbc43890 OCC::DiscoveryMainThread::singleDirectoryJobFinishedWithErrorSlot: void OCC::DiscoveryMainThread::singleDirectoryJobFinishedWithErrorSlot(int, QString) 5 "Unknown error"
06-06 10:22:01:367 0x7fdbbe1e02f0 OCC::DiscoveryJob::remote_vio_opendir_hook: static csync_vio_handle_t *OCC::DiscoveryJob::remote_vio_opendir_hook(const char *, void *) OCC::DiscoveryJob(0x7fdbbe24aa20) PATH_48Chars_UpperLowerLettersOnly_5Dirs_END/20090325 ...Returned from main thread
06-06 10:22:01:367 0x7fdbbe1e02f0 OCC::DiscoveryJob::remote_vio_opendir_hook: static csync_vio_handle_t *OCC::DiscoveryJob::remote_vio_opendir_hook(const char *, void *) 5 when opening PATH_48Chars_UpperLowerLettersOnly_5Dirs_END/20090325 msg= "Unknown error"
06-06 10:22:01:367 0x7fdbbe1e02f0 csync_ftw: opendir failed for ownclouds://MY_OWNCLOUD_URL/remote.php/webdav/PATH_48Chars_UpperLowerLettersOnly_5Dirs_END/20090325 - errno 5
06-06 10:22:01:367 0x7fdbbe1e02f0 OCC::DiscoveryJob::remote_vio_closedir_hook: static void OCC::DiscoveryJob::remote_vio_closedir_hook(csync_vio_handle_t *, void *) OCC::DiscoveryJob(0x7fdbbe24aa20) "/PATH_48Chars_UpperLowerLettersOnly_5Dirs_END"
06-06 10:22:01:367 0x7fdbbe1e02f0 OCC::DiscoveryJob::remote_vio_closedir_hook: static void OCC::DiscoveryJob::remote_vio_closedir_hook(csync_vio_handle_t *, void *) OCC::DiscoveryJob(0x7fdbbe24aa20) "/MJNCJ_FamilyShared/OldBackups/f/Pictures"
06-06 10:22:01:367 0x7fdbbe1e02f0 OCC::DiscoveryJob::remote_vio_closedir_hook: static void OCC::DiscoveryJob::remote_vio_closedir_hook(csync_vio_handle_t *, void *) OCC::DiscoveryJob(0x7fdbbe24aa20) "/MJNCJ_FamilyShared/OldBackups/f"
06-06 10:22:01:367 0x7fdbbe1e02f0 OCC::DiscoveryJob::remote_vio_closedir_hook: static void OCC::DiscoveryJob::remote_vio_closedir_hook(csync_vio_handle_t *, void *) OCC::DiscoveryJob(0x7fdbbe24aa20) "/MJNCJ_FamilyShared/OldBackups"
06-06 10:22:01:368 0x7fdbbe1e02f0 OCC::DiscoveryJob::remote_vio_closedir_hook: static void OCC::DiscoveryJob::remote_vio_closedir_hook(csync_vio_handle_t *, void *) OCC::DiscoveryJob(0x7fdbbe24aa20) "/MJNCJ_FamilyShared"
06-06 10:22:01:368 0x7fdbbe1e02f0 OCC::DiscoveryJob::remote_vio_closedir_hook: static void OCC::DiscoveryJob::remote_vio_closedir_hook(csync_vio_handle_t *, void *) OCC::DiscoveryJob(0x7fdbbe24aa20) ""
06-06 10:22:01:369 0x7fdbbe1e02f0 csync_statedb_close: sqlite3_close=0
06-06 10:22:01:369 0x7fdbbbc43890 OCC::SyncEngine::handleSyncError:  #### ERROR during  csync_update :  "An error occurred while opening a directory Unknown error"
06-06 10:22:01:479 0x7fdbbbc43890 OCC::SyncEngine::finalize: CSync run took  59703
06-06 10:22:01:479 0x7fdbbbc43890 OCC::Folder::slotSyncFinished: -> SyncEngine finished with ERROR, warn count is 0
06-06 10:22:01:480 0x7fdbbbc43890 OCC::Folder::bubbleUpSyncResult: Processing result list and logging took  1  Milliseconds.
06-06 10:22:01:480 0x7fdbbbc43890 OCC::Folder::bubbleUpSyncResult: OO folder slotSyncFinished: result:  1
06-06 10:22:01:481 0x7fdbbbc43890 OCC::Folder::slotSyncFinished:   ** error Strings:  ("An error occurred while opening a directory Unknown error")
06-06 10:22:01:481 0x7fdbbbc43890 OCC::Folder::slotSyncFinished:     * owncloud csync thread finished with error
06-06 10:22:01:481 0x7fdbbbc43890 OCC::Folder::slotSyncFinished: the last 1 syncs failed
06-06 10:22:01:481 0x7fdbbbc43890 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:ERROR:/Users/USERNAME/ownCloud/"
06-06 10:22:01:481 0x7fdbbbc43890 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "UPDATE_VIEW:/Users/USERNAME/ownCloud/"
06-06 10:22:01:483 0x7fdbbbc43890 OCC::ownCloudGui::slotComputeOverallSyncStatus: Folder in overallStatus Message:  OCC::Folder(0x7fdbbe10be50)  with name  "ownCloud"
06-06 10:22:01:483 0x7fdbbbc43890 OCC::ownCloudGui::slotSyncStateChange: Sync state changed for folder  "ownCloud" :  "Error"
06-06 10:22:01:684 0x7fdbbbc43890 OCC::FolderMan::slotFolderSyncFinished: <===================================== sync finished for  "ownCloud"

**Comment by TheOtterslider** [comment]
I should add that if you don't think this is related to the original, I can do a new report with details

**Comment by guruz** [comment]
@TheOtterslider Yes, please create a new report and @ CC me.. thanks..

**Comment by TheOtterslider** [comment]
New issue report:  3313:  https://github.com/owncloud/client/issues/3313
