### ISSUE TITLE
Explicit selection of a big folder to sync has to be confirmed a second time

### ISSUE THREAD

**Issue by phil-davis** [owncloud/client#3560]
### Steps to reproduce
1. Set confirmation limit to some low size for testing (e.g. 1 MB)
2. Create a folder and put a file in it bigger than the limit, let it sync up to the server
3. Deselect the folder from the list of folders to sync and apply (the folder will be deleted on the client)
(or do whatever steps 1,2,3 you like to get a big folder on the server that is not currently being synced to the client)
4. Select the folder in the "folders to sync" and apply.

### Expected behaviour
The folder should automatically start synching down from server to client, because the user has just used the interactive UI and explicitly asked to sync.

### Actual behaviour
The user is notified "There are new shared folders that were not synchronized because they are to big: ownCloud/Xyz" and then has to select the folder for sync a 2nd time.

Users will be surprised by that, I was! I think that when the user has explicitly selected the folder to sync and presses Apply, the folder should download without further user interaction.

This will happen in real life when a user first decides not to sync a new big folder that comes on the server, then some time later decides to sync it.

### Server configuration
ownCloud version: 8.0

### Client configuration
Client version: 2.0.0.5351

Operating system: Windows10

OS language: English (US)

Installation path of client: default

**Comment by ogoffart** [comment]
Should be fixed with 952c24903936586e2bd17e056d71b17ac2eb7957

**Comment by phil-davis** [comment]
I am available to test, but we are on Windows and no Windows build has appeared for some time. Is the Windows nightly builder stuck/broken?

**Comment by ogoffart** [comment]
I think the build server are down at the moment,  they should be back at some point.

**Comment by phil-davis** [comment]
Windows client 2.0.0.5359
1. On the server in userA I make a new big folder Xyz and share it to userB.
2. userB client gives me the notice about a big folder Xyz. I choose not to sync it and press Apply - all good.
3. 5 minutes later I decide "oh, I want that folder". On the client I open the dropdown of folders to sync, select Xyz and press Apply - good.
4. The client starts discovery... and then displays the message about:
"There are new folders that were not synchronized because they are too big: ownCloud/Xyz/"
Point 4 is still a problem - it should just sync down the big folder without any further userinteraction.

I wonder, did that change actually get into this build?

**Comment by phil-davis** [comment]
Now tested with 2.0.0.5361 and still get the same 4-step sequence and issue described above.

**Comment by ogoffart** [comment]
I see.  I'll have to put the folders in the white list when checking them with selective sync.

**Comment by phil-davis** [comment]
Behaviour is the same with 2.0.0.5367.
Let me know when you have more code ready for test. (Hmmm - I should get used to just looking at the issue labels.

**Comment by phil-davis** [comment]
ownCloud client 2.0.0.5381 on Windows 10 works fine.
Folder previously not being synced. Select to sync it. Apply. It starts downloading without further user input.
Thanks.

**Comment by feli74** [comment]
I am experiencing the same issue with the linux client 2.0.1 on ubuntu 14.04. Any recommendations?

**Comment by nikparo** [comment]
I've noticed that if a sync is already ongoing, and I select some folders bigger than the threshold, they are automatically deselected as being too big (and I get the warning again) when the sync restarts after clicking 'apply'.

OwnCloud Version 2.2.4 (build 3709) on Mac
