### ISSUE TITLE
[Windows] "Connection Closed" since update to 2.0.2

### ISSUE THREAD

**Issue by brunodegoyrans** [owncloud/client#4047]
Hi

My client had been automatically updated.
Just after restart, the client asked for a sync folder location (known issue: https://forum.owncloud.org/viewtopic.php?f=14&t=31191).

Since then, I have messages "connexion closed" and "Operation cancelled" for 3 files,
then Sync stops.

**Comment by guruz** [comment]
Did you also update the server?
What is in the server's owncloud.log?
Which OS are you on?

**Comment by jbb0906** [comment]
I just recently experienced a similar problem. Following an automatic update of the client to 2.0.2, on a Windows 10 computer, It asked me to reselect the sync folder, and when I did, everything worked fine; but, when I the same update was done on my Win 7 computer, I keep getting an error saying that "there were new folders that were not synchronized because they are too big: documents/"
There have been no recent changes to my server, and the update worked on one computer, but not the other.

**Comment by phil-davis** [comment]
@jbb0906 If documents is bigger than 500MB (the initial default for the big folder limit) then it should ask you the first time if you want to sync it. You can change that limit in the General settings tab. So it might be "normal" (given the other issues with have to re-add the folder sync connections after an automatic upgrade) for it to prompt again about big folders.

**Comment by jbb0906** [comment]
Thanks. I looked everywhere EXCEPT for that one little check box. I´ve unchecked it, so hopefully that will solve the problem. Thanks for the prompt reply.

**Comment by brunodegoyrans** [comment]
@guruz 
Thank you for your help.

No, I didn't update the server yet to 8.2. This is still 8.1.3
OS is DEBIAN LINUX 7 on server side, WINDOWS 10 on client side.

I have copied below the last events in owncloud.log.
As you can see, there are errors about folder "Article 166" and files 1.skp,1.skb, 1.png.
This is these files that are shown as error in the client:
- 02/11/2015 13:55:06 BILP/Activité CABANE/Images pour le guide CABANE/Article 166/1.skp    E:owncloud    Operation canceled
- 02/11/2015 13:55:06 BILP/Activité CABANE/Images pour le guide CABANE/Article 166/1.skb    E:owncloud    Operation canceled
- 02/11/2015 13:55:06 BILP/Activité CABANE/Images pour le guide CABANE/Article 166/1.png    E:owncloud    Connexion fermée

When I look in the sync folder on my PC, where these files are stored, I see 3 additionnal files:
.1.png.~555b
.1.skb.~333e
.1.skp.~302f
that are temporary donwloads I think.

{"reqId":"J6UG0wzAB8cTv83sJ2Pz","remoteAddr":"89.234.156.29","app":"files_locking","message":"INFO: Read lock requested for \/data\/owncloud\/bruno\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.png","level":0,"time":"2015-11-02T12:55:00+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.png"}
{"reqId":"J6UG0wzAB8cTv83sJ2Pz","remoteAddr":"89.234.156.29","app":"files_locking","message":"PASS: Acquired read lock for \/data\/owncloud\/bruno\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.png","level":0,"time":"2015-11-02T12:55:00+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.png"}
{"reqId":"J6UG0wzAB8cTv83sJ2Pz","remoteAddr":"89.234.156.29","app":"files_locking","message":"INFO: Incrementing lock type 1 count for \/data\/owncloud\/bruno\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.png","level":0,"time":"2015-11-02T12:55:00+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.png"}
{"reqId":"J6UG0wzAB8cTv83sJ2Pz","remoteAddr":"89.234.156.29","app":"files_locking","message":"INFO: Incrementing lock type 1 count for \/data\/owncloud\/bruno\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.png","level":0,"time":"2015-11-02T12:55:00+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.png"}
{"reqId":"J6UG0wzAB8cTv83sJ2Pz","remoteAddr":"89.234.156.29","app":"files_locking","message":"INFO: Incrementing lock type 1 count for \/data\/owncloud\/bruno\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.png","level":0,"time":"2015-11-02T12:55:00+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.png"}
{"reqId":"9pXcUfAc5KjHSIzPoeyc","remoteAddr":"89.234.156.29","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(149): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(122): OC\\\\Connector\\\\Sabre\\\\Auth->auth(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): OC\\\\Connector\\\\Sabre\\\\Auth->authenticate(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/owncloud\\\/remote.php(132): require_once('\\\/var\\\/www\\\/ownclo...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":70}","level":0,"time":"2015-11-02T12:55:00+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.skp"}
{"reqId":"VvczxBMRuCXdxPsU0hLA","remoteAddr":"89.234.156.29","app":"files_locking","message":"INFO: Read lock requested for \/data\/owncloud\/bruno\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.skb","level":0,"time":"2015-11-02T12:55:01+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.skb"}
{"reqId":"VvczxBMRuCXdxPsU0hLA","remoteAddr":"89.234.156.29","app":"files_locking","message":"PASS: Acquired read lock for \/data\/owncloud\/bruno\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.skb","level":0,"time":"2015-11-02T12:55:01+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.skb"}
{"reqId":"VvczxBMRuCXdxPsU0hLA","remoteAddr":"89.234.156.29","app":"files_locking","message":"INFO: Incrementing lock type 1 count for \/data\/owncloud\/bruno\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.skb","level":0,"time":"2015-11-02T12:55:01+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.skb"}
{"reqId":"\/VhKa2X5uwXISBN\/Re9X","remoteAddr":"89.234.156.29","app":"files_locking","message":"INFO: Read lock requested for \/data\/owncloud\/bruno\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.skp","level":0,"time":"2015-11-02T12:55:01+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.skp"}
{"reqId":"\/VhKa2X5uwXISBN\/Re9X","remoteAddr":"89.234.156.29","app":"files_locking","message":"PASS: Acquired read lock for \/data\/owncloud\/bruno\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.skp","level":0,"time":"2015-11-02T12:55:01+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.skp"}
{"reqId":"\/VhKa2X5uwXISBN\/Re9X","remoteAddr":"89.234.156.29","app":"files_locking","message":"INFO: Incrementing lock type 1 count for \/data\/owncloud\/bruno\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.skp","level":0,"time":"2015-11-02T12:55:01+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.skp"}
{"reqId":"\/VhKa2X5uwXISBN\/Re9X","remoteAddr":"89.234.156.29","app":"files_locking","message":"INFO: Incrementing lock type 1 count for \/data\/owncloud\/bruno\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.skp","level":0,"time":"2015-11-02T12:55:01+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.skp"}
{"reqId":"\/VhKa2X5uwXISBN\/Re9X","remoteAddr":"89.234.156.29","app":"files_locking","message":"INFO: Incrementing lock type 1 count for \/data\/owncloud\/bruno\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.skp","level":0,"time":"2015-11-02T12:55:01+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.skp"}
{"reqId":"VvczxBMRuCXdxPsU0hLA","remoteAddr":"89.234.156.29","app":"files_locking","message":"INFO: Incrementing lock type 1 count for \/data\/owncloud\/bruno\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.skb","level":0,"time":"2015-11-02T12:55:01+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.skb"}
{"reqId":"VvczxBMRuCXdxPsU0hLA","remoteAddr":"89.234.156.29","app":"files_locking","message":"INFO: Incrementing lock type 1 count for \/data\/owncloud\/bruno\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.skb","level":0,"time":"2015-11-02T12:55:01+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.skb"}
{"reqId":"J6UG0wzAB8cTv83sJ2Pz","remoteAddr":"89.234.156.29","app":"files_locking","message":"INFO: Read lock requested for \/data\/owncloud\/bruno\/files_encryption\/keys\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.png\/OC_DEFAULT_MODULE\/fileKey","level":0,"time":"2015-11-02T12:55:01+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.png"}
{"reqId":"J6UG0wzAB8cTv83sJ2Pz","remoteAddr":"89.234.156.29","app":"files_locking","message":"PASS: Acquired read lock for \/data\/owncloud\/bruno\/files_encryption\/keys\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.png\/OC_DEFAULT_MODULE\/fileKey","level":0,"time":"2015-11-02T12:55:01+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.png"}
{"reqId":"J6UG0wzAB8cTv83sJ2Pz","remoteAddr":"89.234.156.29","app":"files_locking","message":"INFO: Incrementing lock type 1 count for \/data\/owncloud\/bruno\/files_encryption\/keys\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.png\/OC_DEFAULT_MODULE\/fileKey","level":0,"time":"2015-11-02T12:55:01+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.png"}
{"reqId":"\/VhKa2X5uwXISBN\/Re9X","remoteAddr":"89.234.156.29","app":"files_locking","message":"INFO: Read lock requested for \/data\/owncloud\/bruno\/files_encryption\/keys\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.skp\/OC_DEFAULT_MODULE\/fileKey","level":0,"time":"2015-11-02T12:55:01+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.skp"}
{"reqId":"\/VhKa2X5uwXISBN\/Re9X","remoteAddr":"89.234.156.29","app":"files_locking","message":"PASS: Acquired read lock for \/data\/owncloud\/bruno\/files_encryption\/keys\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.skp\/OC_DEFAULT_MODULE\/fileKey","level":0,"time":"2015-11-02T12:55:01+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.skp"}
{"reqId":"\/VhKa2X5uwXISBN\/Re9X","remoteAddr":"89.234.156.29","app":"files_locking","message":"INFO: Incrementing lock type 1 count for \/data\/owncloud\/bruno\/files_encryption\/keys\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.skp\/OC_DEFAULT_MODULE\/fileKey","level":0,"time":"2015-11-02T12:55:01+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.skp"}
{"reqId":"VvczxBMRuCXdxPsU0hLA","remoteAddr":"89.234.156.29","app":"files_locking","message":"INFO: Read lock requested for \/data\/owncloud\/bruno\/files_encryption\/keys\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.skb\/OC_DEFAULT_MODULE\/fileKey","level":0,"time":"2015-11-02T12:55:01+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.skb"}
{"reqId":"VvczxBMRuCXdxPsU0hLA","remoteAddr":"89.234.156.29","app":"files_locking","message":"PASS: Acquired read lock for \/data\/owncloud\/bruno\/files_encryption\/keys\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.skb\/OC_DEFAULT_MODULE\/fileKey","level":0,"time":"2015-11-02T12:55:01+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.skb"}
{"reqId":"VvczxBMRuCXdxPsU0hLA","remoteAddr":"89.234.156.29","app":"files_locking","message":"INFO: Incrementing lock type 1 count for \/data\/owncloud\/bruno\/files_encryption\/keys\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.skb\/OC_DEFAULT_MODULE\/fileKey","level":0,"time":"2015-11-02T12:55:01+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.skb"}
{"reqId":"VvczxBMRuCXdxPsU0hLA","remoteAddr":"89.234.156.29","app":"files_locking","message":"INFO: Incrementing lock type 1 count for \/data\/owncloud\/bruno\/files_encryption\/keys\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.skb\/OC_DEFAULT_MODULE\/fileKey","level":0,"time":"2015-11-02T12:55:01+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.skb"}
{"reqId":"VvczxBMRuCXdxPsU0hLA","remoteAddr":"89.234.156.29","app":"files_locking","message":"INFO: Read lock requested for \/data\/owncloud\/bruno\/files_encryption\/keys\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.skb\/OC_DEFAULT_MODULE\/bruno.shareKey","level":0,"time":"2015-11-02T12:55:01+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.skb"}
{"reqId":"VvczxBMRuCXdxPsU0hLA","remoteAddr":"89.234.156.29","app":"files_locking","message":"PASS: Acquired read lock for \/data\/owncloud\/bruno\/files_encryption\/keys\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.skb\/OC_DEFAULT_MODULE\/bruno.shareKey","level":0,"time":"2015-11-02T12:55:01+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.skb"}
{"reqId":"VvczxBMRuCXdxPsU0hLA","remoteAddr":"89.234.156.29","app":"files_locking","message":"INFO: Incrementing lock type 1 count for \/data\/owncloud\/bruno\/files_encryption\/keys\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.skb\/OC_DEFAULT_MODULE\/bruno.shareKey","level":0,"time":"2015-11-02T12:55:01+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.skb"}
{"reqId":"VvczxBMRuCXdxPsU0hLA","remoteAddr":"89.234.156.29","app":"files_locking","message":"INFO: Incrementing lock type 1 count for \/data\/owncloud\/bruno\/files_encryption\/keys\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.skb\/OC_DEFAULT_MODULE\/bruno.shareKey","level":0,"time":"2015-11-02T12:55:01+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.skb"}
{"reqId":"J6UG0wzAB8cTv83sJ2Pz","remoteAddr":"89.234.156.29","app":"files_locking","message":"INFO: Incrementing lock type 1 count for \/data\/owncloud\/bruno\/files_encryption\/keys\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.png\/OC_DEFAULT_MODULE\/fileKey","level":0,"time":"2015-11-02T12:55:01+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.png"}
{"reqId":"J6UG0wzAB8cTv83sJ2Pz","remoteAddr":"89.234.156.29","app":"files_locking","message":"INFO: Read lock requested for \/data\/owncloud\/bruno\/files_encryption\/keys\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.png\/OC_DEFAULT_MODULE\/bruno.shareKey","level":0,"time":"2015-11-02T12:55:01+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.png"}
{"reqId":"J6UG0wzAB8cTv83sJ2Pz","remoteAddr":"89.234.156.29","app":"files_locking","message":"PASS: Acquired read lock for \/data\/owncloud\/bruno\/files_encryption\/keys\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.png\/OC_DEFAULT_MODULE\/bruno.shareKey","level":0,"time":"2015-11-02T12:55:01+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.png"}
{"reqId":"J6UG0wzAB8cTv83sJ2Pz","remoteAddr":"89.234.156.29","app":"files_locking","message":"INFO: Incrementing lock type 1 count for \/data\/owncloud\/bruno\/files_encryption\/keys\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.png\/OC_DEFAULT_MODULE\/bruno.shareKey","level":0,"time":"2015-11-02T12:55:01+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.png"}
{"reqId":"\/VhKa2X5uwXISBN\/Re9X","remoteAddr":"89.234.156.29","app":"files_locking","message":"INFO: Incrementing lock type 1 count for \/data\/owncloud\/bruno\/files_encryption\/keys\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.skp\/OC_DEFAULT_MODULE\/fileKey","level":0,"time":"2015-11-02T12:55:01+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.skp"}
{"reqId":"\/VhKa2X5uwXISBN\/Re9X","remoteAddr":"89.234.156.29","app":"files_locking","message":"INFO: Read lock requested for \/data\/owncloud\/bruno\/files_encryption\/keys\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.skp\/OC_DEFAULT_MODULE\/bruno.shareKey","level":0,"time":"2015-11-02T12:55:01+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.skp"}
{"reqId":"\/VhKa2X5uwXISBN\/Re9X","remoteAddr":"89.234.156.29","app":"files_locking","message":"PASS: Acquired read lock for \/data\/owncloud\/bruno\/files_encryption\/keys\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.skp\/OC_DEFAULT_MODULE\/bruno.shareKey","level":0,"time":"2015-11-02T12:55:01+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.skp"}
{"reqId":"\/VhKa2X5uwXISBN\/Re9X","remoteAddr":"89.234.156.29","app":"files_locking","message":"INFO: Incrementing lock type 1 count for \/data\/owncloud\/bruno\/files_encryption\/keys\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.skp\/OC_DEFAULT_MODULE\/bruno.shareKey","level":0,"time":"2015-11-02T12:55:01+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.skp"}
{"reqId":"J6UG0wzAB8cTv83sJ2Pz","remoteAddr":"89.234.156.29","app":"files_locking","message":"INFO: Incrementing lock type 1 count for \/data\/owncloud\/bruno\/files_encryption\/keys\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.png\/OC_DEFAULT_MODULE\/bruno.shareKey","level":0,"time":"2015-11-02T12:55:01+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.png"}
{"reqId":"\/VhKa2X5uwXISBN\/Re9X","remoteAddr":"89.234.156.29","app":"files_locking","message":"INFO: Incrementing lock type 1 count for \/data\/owncloud\/bruno\/files_encryption\/keys\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.skp\/OC_DEFAULT_MODULE\/bruno.shareKey","level":0,"time":"2015-11-02T12:55:01+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.skp"}
{"reqId":"g7dZbS9xSnF+OVtDErvs","remoteAddr":"89.234.156.29","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(149): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(122): OC\\\\Connector\\\\Sabre\\\\Auth->auth(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): OC\\\\Connector\\\\Sabre\\\\Auth->authenticate(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/owncloud\\\/remote.php(132): require_once('\\\/var\\\/www\\\/ownclo...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":70}","level":0,"time":"2015-11-02T12:55:05+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}

**Comment by guruz** [comment]
@brunodegoyrans If you set bandwidth limiting in the settings to "Automatic" will it change anything?

**Comment by brunodegoyrans** [comment]
@guruz 
I did set to automatic (both up and down) but it doesnt change anything.

As I mentionned, when I look in the sync folder on my PC, where these files are stored, I see 3 additionnal files:
.1.png.~555b
.1.skb.~333e
.1.skp.~302f

These temporary files have the exact size of the existing 1.png, 1.skb, 1.skp and they are dated of today.
It seems that the client "thinks" this is a new sync folder and it download the files (by 3) then it tries to rename them to their real name. But since the files are already there, it crashes.

Can someone confirm that behaviour?

**Comment by guruz** [comment]
@brunodegoyrans You mean really exact/correct size down to _byte_ level?
The ```Connection closed``` (```Connexion fermée```) is a network error though, not a rename error.

Could you start the client with a logfile (https://doc.owncloud.org/desktop/2.0/troubleshooting.html#saving-files-directly) and then immediatly after the error quit it to keep the log file size down.
Then try to find the ```Connexion fermée``` in the log and look for the lines before if there is any hints with regards to the file size.

Also something to try: Does it work with 1.8.4? (Download see https://owncloud.org/changelog/desktop/ )

**Comment by brunodegoyrans** [comment]
@guruz 
The files are binary equal.
e.g. .1.png.~555b is totally equal to 1.png

In one of my previous message, I put the content of owncloud.log regarding these files (Article 166/1.*).
I don't see "Connexion fermée" but I see this error ""Message\":\"HTTP\\/1.1 401 No basic authentication headers were found\".
I don't know if it is the cause?

I will try the previous 1.8.4

**Comment by brunodegoyrans** [comment]
@guruz 
I have tried 1.8.4 -> same errors

**Comment by guruz** [comment]
We have an untested nightly with the Qt patch https://gist.github.com/guruz/2cdba6657acb731de713 here: https://download.owncloud.com/desktop/daily/ownCloud-2.0.2.0git-setup.exe
I wonder if that fixes it for you or if we need to look into the server?

**Comment by brunodegoyrans** [comment]
Hi

I have installed 202git. I have still "Connexion fermée", but only on one file. And the synchronization is still bloqued.

I thnik I should start a complete resynchronisation from 0. I mean uninstalle the client, delete the current sync folder. Re-installe. Re-sync

**Comment by guruz** [comment]
@brunodegoyrans I'd more suspect the problem then at the server side (either configuration or webserver modules or owncloud apps or owncloud server itself)

**Comment by brunodegoyrans** [comment]
@guruz 

So I have started a complete re-synchronization from scratch.
And guess what? client shows the same issue "Operation canceled" on the same files.

I 'am not convinced that it is on the server side for these reasons:
- this anomaly had appeared JUST after the installation of the new 2.0.2
- I can download these files from the web panel.
- client can also download these files in a temporary (e.g. 1.png -> .1.png.~22e6) and 1.png is binary equal with .1.png.~22e6
So there is something wrong happening just after the download of a file. This file is present in the sync folder, as temporary file, it has just to be renamed to his actual name. But THIS doesnt work. WHY?


I'am totally bloqued and desperate.

**Comment by brunodegoyrans** [comment]
When the error happens on the client, I don't have error on the SERVER side.
I just have this below. It seems normal? or what?
Extract from owncloud.log for one of the file that produces the issue:

{"reqId":"si6IZrqbjZnqlou4pfDd","remoteAddr":"89.234.156.29","app":"files_locking","message":"INFO: Read lock requested for \/data\/owncloud\/bruno\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.skp","level":0,"time":"2015-11-04T11:15:58+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.skp"}
{"reqId":"si6IZrqbjZnqlou4pfDd","remoteAddr":"89.234.156.29","app":"files_locking","message":"PASS: Acquired read lock for \/data\/owncloud\/bruno\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.skp","level":0,"time":"2015-11-04T11:15:58+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.skp"}
{"reqId":"si6IZrqbjZnqlou4pfDd","remoteAddr":"89.234.156.29","app":"files_locking","message":"INFO: Incrementing lock type 1 count for \/data\/owncloud\/bruno\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.skp","level":0,"time":"2015-11-04T11:15:58+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.skp"}
{"reqId":"si6IZrqbjZnqlou4pfDd","remoteAddr":"89.234.156.29","app":"files_locking","message":"INFO: Incrementing lock type 1 count for \/data\/owncloud\/bruno\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.skp","level":0,"time":"2015-11-04T11:15:58+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.skp"}
{"reqId":"si6IZrqbjZnqlou4pfDd","remoteAddr":"89.234.156.29","app":"files_locking","message":"INFO: Incrementing lock type 1 count for \/data\/owncloud\/bruno\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.skp","level":0,"time":"2015-11-04T11:15:58+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.skp"}
{"reqId":"si6IZrqbjZnqlou4pfDd","remoteAddr":"89.234.156.29","app":"files_locking","message":"INFO: Read lock requested for \/data\/owncloud\/bruno\/files_encryption\/keys\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.skp\/OC_DEFAULT_MODULE\/fileKey","level":0,"time":"2015-11-04T11:15:58+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.skp"}
{"reqId":"si6IZrqbjZnqlou4pfDd","remoteAddr":"89.234.156.29","app":"files_locking","message":"PASS: Acquired read lock for \/data\/owncloud\/bruno\/files_encryption\/keys\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.skp\/OC_DEFAULT_MODULE\/fileKey","level":0,"time":"2015-11-04T11:15:58+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.skp"}
{"reqId":"si6IZrqbjZnqlou4pfDd","remoteAddr":"89.234.156.29","app":"files_locking","message":"INFO: Incrementing lock type 1 count for \/data\/owncloud\/bruno\/files_encryption\/keys\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.skp\/OC_DEFAULT_MODULE\/fileKey","level":0,"time":"2015-11-04T11:15:58+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.skp"}
{"reqId":"si6IZrqbjZnqlou4pfDd","remoteAddr":"89.234.156.29","app":"files_locking","message":"INFO: Incrementing lock type 1 count for \/data\/owncloud\/bruno\/files_encryption\/keys\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.skp\/OC_DEFAULT_MODULE\/fileKey","level":0,"time":"2015-11-04T11:15:58+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.skp"}
{"reqId":"si6IZrqbjZnqlou4pfDd","remoteAddr":"89.234.156.29","app":"files_locking","message":"INFO: Read lock requested for \/data\/owncloud\/bruno\/files_encryption\/keys\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.skp\/OC_DEFAULT_MODULE\/bruno.shareKey","level":0,"time":"2015-11-04T11:15:58+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.skp"}
{"reqId":"si6IZrqbjZnqlou4pfDd","remoteAddr":"89.234.156.29","app":"files_locking","message":"PASS: Acquired read lock for \/data\/owncloud\/bruno\/files_encryption\/keys\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.skp\/OC_DEFAULT_MODULE\/bruno.shareKey","level":0,"time":"2015-11-04T11:15:58+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.skp"}
{"reqId":"si6IZrqbjZnqlou4pfDd","remoteAddr":"89.234.156.29","app":"files_locking","message":"INFO: Incrementing lock type 1 count for \/data\/owncloud\/bruno\/files_encryption\/keys\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.skp\/OC_DEFAULT_MODULE\/bruno.shareKey","level":0,"time":"2015-11-04T11:15:58+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.skp"}
{"reqId":"si6IZrqbjZnqlou4pfDd","remoteAddr":"89.234.156.29","app":"files_locking","message":"INFO: Incrementing lock type 1 count for \/data\/owncloud\/bruno\/files_encryption\/keys\/files\/BILP\/Activit\u00e9 CABANE\/Images pour le guide CABANE\/Article 166\/1.skp\/OC_DEFAULT_MODULE\/bruno.shareKey","level":0,"time":"2015-11-04T11:15:58+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/BILP\/Activit%C3%A9%20CABANE\/Images%20pour%20le%20guide%20CABANE\/Article%20166\/1.skp"}

**Comment by brunodegoyrans** [comment]
Now I have new kind of errors "Broken webserver..." on the client,
but still on the same files:

04/11/2015 14:35:54BILP/Activité CABANE/Images pour le guide CABANE/Article 166/2.skpE:\ownCloud                   Operation canceled1 Mo      
04/11/2015 14:35:54BILP/Activité CABANE/Images pour le guide CABANE/Article 166/2.skbE:\ownCloud                   Operation canceled1 Mo      
04/11/2015 14:35:54BILP/Activité CABANE/Images pour le guide CABANE/Article 166/2.pngE:\ownCloud                   Connexion fermée387 Ko    
04/11/2015 14:35:49BILP/Activité CABANE/Images pour le guide CABANE/Article 166/1.skpE:\ownCloud                   Broken webserver returning empty content length for non-empty file on resume1,2 Mo    
04/11/2015 14:35:48BILP/Activité CABANE/Images pour le guide CABANE/Article 166/1.skbE:\ownCloud                   Broken webserver returning empty content length for non-empty file on resume1,2 Mo    
04/11/2015 14:35:48BILP/Activité CABANE/Images pour le guide CABANE/Article 166/1.pngE:\ownCloud                   Broken webserver returning empty content length for non-empty file on resume316 Ko

**Comment by brunodegoyrans** [comment]
The folder with error was "Article 166".
I delete it with the Web interface of Owncloud.
Then I upload it again, still with the WEB interface.
And guess what? All files from "Article 166" had been correctly uploaded into my sync folder.
But Now, the problem occurs on the next folder "Article 185"

According to these symptoms, It is clear that it is a logical problem inside Owncloud, either client or server, maybe both.

**Comment by guruz** [comment]
@brunodegoyrans Note that server 8.1.4 and 8.2.x are already released..

The ```Broken webserver``` message really leads to thinking that this is a server/configuration issue.
https://github.com/owncloud/client/blob/251679253ae5304f5012ad8dea50898c4bbcf7da/src/libsync/propagatedownload.cpp#L524

@J-A-M has seen this in https://github.com/owncloud/client/issues/4000
@raivisdejus has seen this in https://github.com/owncloud/client/issues/3848
@andi-at and @maxstricker got this in https://github.com/owncloud/client/issues/3816

FYI @PVince81 Maybe you have seen this

**Comment by guruz** [comment]
Do you use the encryption or version app?
https://github.com/owncloud/core/issues/20234#issuecomment-153682302


FYI @schiesbn

**Comment by volp3** [comment]
regarding <a href="https://github.com/owncloud/core/issues/20234">#20234</a>, i actually face the exact same problem @brunodegoyrans 
autoupdater got me to 2.0.2 and boom same error
 I could "solve" the problem by excluding the damaged(?) folders from sync, then everything went smooth. Strange coincidence: All folders (4 of 12) with broken files were above the size limit and it didn't prompt any confirm request (unchanged 500mb default)
checked php, apache, and oc server log, no error in any of them when the "broken webserver returning" error in the client strikes

**Comment by brunodegoyrans** [comment]
@guruz 
I use encryption and version app.
I have upgraded to 8.1.4, but errors remain.
The problem occurs with ALL the files that were uploaded before client 2.0.2
With files recently uploaded: NO problem

Please, read this below carrefully:
As I already said, file is downloaded into sync folder with a temporary name. This downloaded file is OK. The content is exactly what it should be. But just after, client shows an error.
This means that the server has correctly sent the file.
But client can't rename it, or has saw something on server that makes it throwing an error.

The broken webserver message has appeared only few times. Not each time the client shows errors.

**Comment by brunodegoyrans** [comment]
@guruz 

I suspect either encryption or versionning more probably.

Because the difference between the files that can be sync and the ones that cannot be sync is the number of versions on the server:
the ones that work had been uploaded on the server recently. There is only one version for each.
the ones that make error may have multiple version.

I think encryption works since I can download all the files with the web interface.

**Comment by schiesbn** [comment]
@brunodegoyrans  The number of the versions shouldn't be the problem. But as described in the other issue @guruz linked to, we had a problem that we don't kept the right file size in the cache when versions are created/restored. In this case the size in the cache was the encrypted size and not the unencrypted size. Because the encrypted size is always larger the sync client thought that the download was interrupted.

Maybe you can double check. If it also happens with new files, also if you upload them multiple times to create versions or if it only happens once you restored a version.

**Comment by brunodegoyrans** [comment]
@schiesbn 
I have created a new file. A small txt file.
then I uploaded it with the WEB interface
the client had correctly downloaded the new file into my sync folder.
I have modified the file into the sync folder
then the client did the update on the server.
On the WEB interface, I can see the 2 versions.

Now I restore the 1st version, with the WEB interface.
Few minutes later, the 1st version is also on the sync folder.

Conclusion : versionning works on new files. But on old files (before installation of 2.0.2) NOTHING works, errors "Operation canceled', "Connexion fermée".

**Comment by brunodegoyrans** [comment]
@guruz 
Why did you remove this issue from 2.1.1-nextpacht?

Is my problem taken into account? what can I do to help team?
I can give access to my server if needed? I can do additionnal tests if required.

I know this is not the place to cry, but the work with my team is almost stopped. My productivity is down since 2.0.2.
I just would like to be  reassured that this issue is focussed.

**Comment by brunodegoyrans** [comment]
I see another error in owncloud.log (server) that someone else in another post also noticed:
Array to string conversion at /var/www/owncloud/lib/private/template/functions.php#36

**Comment by guruz** [comment]
@brunodegoyrans If level of service is a concern, I suggest to have a look at the support options in https://owncloud.org/changelog/desktop/

I think @schiesbn already pointed out that this is probably fixed by https://github.com/owncloud/core/pull/20288

I hope you can verify this then we can close this bug.

**Comment by brunodegoyrans** [comment]
@guruz 
I don't understand what you suggested about the support options? I have read the page you suggested and didn't see anything that could solve the anomaly.
Or do you want to mention that? https://owncloud.com/get-started-standard-subscription/

https://github.com/owncloud/core/pull/20288 this issue does concern 8.2.
I'am on 8.1.4

We cannot close this bug. I'am bloqued since client 2.0.2. I did nothing on the server side. And as others said, I don't see anything that help in the log file (server or client).
So there is a bug somewhere in owncloud. I can't beleive I'am the only one.

**Comment by guruz** [comment]
@brunodegoyrans The issue above mentions a backport-fix for 8.2.1 https://github.com/owncloud/core/pull/20331
(however those issues also mentions that a cleanup script might be necessary)

**Comment by volp3** [comment]
@brunodegoyrans 
i told you i have the same issue

**Comment by brunodegoyrans** [comment]
@guruz Sorry, I still not understand. You tell about 8.2.1. I'am running 8.1.4

Moreover, I'am not concerned by issues https://github.com/owncloud/core/pull/20288 or https://github.com/owncloud/core/pull/20331
I do NOT have the bugs related by these issues. I don't have problem with versionning. I upload a big file, I upload a new version, I can revert to previous version without problem.

I have problem with ALL the files that where handled before installation of client 2.0.2
With new uploaded files, NO problems.

@guruz  please tell me if you think my problem is an issue of my server, and not an issue in owncloud?

**Comment by brunodegoyrans** [comment]
@volp3 
My issue is not exactly the same since I have no problem with versionning. And I could not solve the problem.
The common things are:
- it started immedialty after the installation and 1st run of 2.0.2
- I don't have any traces in the logs, at the exact time when the "connection closed" message is produced.

**Comment by pongraczi** [comment]
Hello folks, may I join to the club? I have exactly the same issue.
I read all posts on this topic and the symptoms are exactly as you have:
the client is 2.0.2 on linuxmint, server is 8.2, 
The client can download exactly the same file into the temporary file, but client reports as operation cancelled, connection closed.

**Comment by brunodegoyrans** [comment]
@pongraczi WELCOME!

I hope more follks will add their story here.
Because for the moment, dev team seems to not take this issue seriously.
Maybe they have more "important" bugs to solve? 
Maybe they consider owncloud is not the cause. But obviously, it is.

@dev team I'am available for any additionnal informations. I can do some debugging. I can give an access to my server. I can do whatever you want. I'am there, guys.

**Comment by pongraczi** [comment]
Just for the record, I played with these:
- maintenance on the server, refreshing caches, scan all files etc.
- increasing keepalive etc.
doesn't matter.

When I checked problematic file, I found that, the real size is about 26k, but the oc_filecache has about 40k as size of the file, which is definitely not ok.
So, if the client wanted to download 40k but it got only 26k (which is correct otherwise), it run into problem and syncing stuck.

Ok, I checked it, the problem is definitely that, the stored filesize is different from the real filesize.
Rewriting the size of all occurences in the oc_filecache table fixes it.

As I remember, I never used encryption.

**Comment by brunodegoyrans** [comment]
@pongraczi 
This issue is clearly a problem of inconsistency at the last step of downloading.

Strange points are:
- No trace in logs
- No problem when downloading from Web interface. Problem only with windows client.
- Issue suddenly occured just after installing 2.0.2. But problem seems to be on server.
- If I re-install a previous version of client, the issue is still there. So it seems that installation and 1st run of client 2.0.2 had launched a process on server that corrupted all files and/or database.
- problem is not present on files that have been uploaded after 2.0.2

@dev There is a serious problem either on client or server, maybe both.
I'am surprised (and irritated) that we don't have some news since several days.
Is there someone from dev team looking at this issue?
Maybe you don't  have enough people complaining about THIS issue?
I'am pretty sure that if this issue is not solved now, it will explose more largely in a future release.

The only solution I found is to erase all the files on the server and upload them again.
With my slow connection, it will take some weeks.

I have lost enough time and productivity. I can't wait more longer.
But the worse is that I have lost faith and confidence with owncloud (2 majors bugs within few months).

Anyway, I'am available to help dev team.

**Comment by baldurmen** [comment]
I do have to same problem, but only on one of the 2 instances I have. The Owncloud instance that is causing problem is on 8.1, whereas the other one is on 7.04.

I don't have the apache logs yet (I've asked the admins for it) but the logs on the client are not really usefull...

My sync client is on Linux, but I know the same problems happens on Windows too. I'm able to download a few Mb at a time and then the client crashes. Pausing and restarting the sync gets me another few Mb before a crash. 

The most frequent error is the "connection closed" one:

```
11-12 21:18:00:314 0x9a12ef0 OCC::Folder::slotSyncFinished:   ** error Strings:  ("Connection closed", "Operation canceled", "Operation canceled", "Comités/CRAA/ABC et autres lectures pertinentes/Martin Robert - One does not simply raise tuition - Debt and discipline in the human capital ideology - 2012.pdf: Connection closed", "Comités/CRAA/Acadégamique/2010-2011/AcadéGAmique - Réforme.pdf: Operation canceled", "Comités/CRAA/Acadégamique/2010-2011/Rentrée cégep réforme 1.doc: Operation canceled")
11-12 21:18:00:323 0x9a12ef0 OCC::Folder::slotSyncFinished:     * owncloud csync thread finished with error
11-12 21:18:00:324 0x9a12ef0 OCC::Folder::slotSyncFinished: the last 10 syncs failed
```

Sometime I get a "host foo.bar.org not found" error too, but this is rarer and at the moment I am not able to reproduce it to get the logs.

I did also see a few "connection refused".

I am not using encryption nor have ever seen the "broken webserver" error.

**Comment by pongraczi** [comment]
I think the main problem related to this: https://github.com/owncloud/core/pull/20331
I mean, the filecache contains wrong filesize.

**Comment by brunodegoyrans** [comment]
@pongraczi 

This could be the case. Although https://github.com/owncloud/core/pull/20331 only talk about 8.2.x
I have the problem with 8.1.4

**Comment by baldurmen** [comment]
I upgraded to 8.2.1 and still have the same problem.

**Comment by brunodegoyrans** [comment]
@baldurmen 
This is a bad news, but not surprising.

Something happened just after the installation of client 2.0.2.
This "thing" has done something in the server database, the cache, or something else.

I hope someone from dev or support team will come back again into this thread.

The only solution I found is to delete all the folders on the server, from the web interface, then re-upload again. Its like a big RESET. And even with that, I have the above errors as well. But it continues to sync with the next attempts.
This is dirt, time consuming, lost of history and versions. But the worst, it occults the root causes.

**Comment by PVince81** [comment]
For those of you who are using encryption, it is likely to be the "filesize does not match" issue.
Older sync clients ignored that issue and somehow managed to recover from this during the next sync pass. It seems the newer sync client is more strict about filesize.

Here is a ticket about providing a repair script to fix the encrypted files that have mismatched sizes, see https://github.com/owncloud/core/issues/18225

**Comment by baldurmen** [comment]
I am not...

**Comment by Ninos** [comment]
Upgraded client to v2.1.0, server is running v8.2.1 and problem still exists...

**Comment by pongraczi** [comment]
I solved like this:
- stopping the desktop client and purge all files (or just rename the owncloud directory, the point is, your local owncloud folder must be empty)
- downloaded all files from the owncloud website directly, and saved to a temporary folder in my local machine
- deleted all files via the webgui 
- ( optionally delete the account and recreate it)
- start your desktop client - it should be empty
- copy all files from your temporary directory to the empty owncloud folder
- it will upload all files again

Please note, maybe I forget something above, but the point is: delete via the webgui and re-add all existing files to have correct filesize in your database.
I tried to fix the filesize information directly in the DB, but I was tired after 10 instances and I just did the "hard" reset.

**Comment by brunodegoyrans** [comment]
This issue is mainly caused by an inconsistency between the actual size of the file, and the filesize stored in the database. As far as I understood, this bug had appeared during the encryption algorythm migration, during the summer 2015, or something like that.
So when the client had finished downloading, it asks the server for the filesize it should encounter. The server gives the client the filesize stored in database. Since it is wrong, the client considers the file is corrupted and stops: operation canceled.
Sorry, I'am not sure of the details but it is something like that.
This is the cause.

Now let's see the solution:
Some unofficial developpers have made scripts to repair the database: https://github.com/owncloud/core/issues/18225

And recently, an owncloud collaborator has made a final script here: https://gitlab.eqipe.ch/xwave-gmbh/ocfixwrongsizedfiles

**Comment by guruz** [comment]
Let's track in https://github.com/owncloud/client/issues/4326#issuecomment-169282743 for now. It's a combined core/client issue IMHO.
