### ISSUE TITLE
`add folder synchronization` dialog box too short

### ISSUE THREAD

**Issue by martin-rueegg** [owncloud/client#4280]
(client: Version 2.1.0 (build 5683). Windows.)

when adding a new folder synchronization and there is a warning message displayed, the rest of the dialog gets shrunken and unreadable:
<img width="261" alt="new_folder_sync shrunken" src="https://cloud.githubusercontent.com/assets/6409516/11783213/d569f060-a26d-11e5-8021-a34f2fa76d1c.png">

when increasing hight, it's ok:
<img width="261" alt="new_folder_sync enlarged" src="https://cloud.githubusercontent.com/assets/6409516/11783230/fcfe2c7c-a26d-11e5-81c5-f0a97ee7e89c.png">

hight should be increased automatically by the hight of the notification message, or it should be increased in general.

**Comment by martin-rueegg** [comment]
possibly related #3414

**Comment by guruz** [comment]
@michaelstingl @martin-rueegg @jturcotte Is this fixed with the HiDPi improvements in 2.1.1?

**Comment by danimo** [comment]
@guruz No idea, I don't have any HiDPI screen. Let's wait for @martin-rueegg to confirm. It should though.

**Comment by martin-rueegg** [comment]
thanks for asking. unfortunately the OC Client 2.1.0 did not prompt for an update, even after restarting the client it showed to be the "latest version" ...

anyways, have updated to 2.1.1 (build 5837). however, the issue remains:
![oc_add_folder](https://cloud.githubusercontent.com/assets/6409516/13215324/59aaf792-d94c-11e5-90bf-9b7b701b1cd6.JPG)

thank you for your attention!

**Comment by danimo** [comment]
@martin-rueegg We haven't yet enabled the auto-updated. I think you'll need to wait until 2.2.

**Comment by martin-rueegg** [comment]
@danimo, no worries. i just wondered that the information on Allgemein/Updates says that i'm running the latest version (even though i wasn't).
if an information is given, i would expect it to be accurate, regardless of whether auto-update itself is performed. however, if no check is performed, i would expect no information is given in the first place ... ;-)
but that's an other issue. thanks for your comment anyway!

**Comment by jturcotte** [comment]
Let's see if the move to Qt 5.6 helps.

**Comment by guruz** [comment]
https://owncloud.org/changelog/desktop/ 2.3 is out which might fix this

**Comment by martin-rueegg** [comment]
Yes partially it is fixed, apart from this dialog:

![image](https://cloud.githubusercontent.com/assets/6409516/23557028/7fe53e98-0026-11e7-8304-2ad55c115cd8.png)

vs.

![image](https://cloud.githubusercontent.com/assets/6409516/23557006/68dde6d2-0026-11e7-813c-249bc40aca7b.png)

It seems, the list and the button have no minimal height, just the container, they're sitting in. And with the error message, this container does not provide enough height and the buttons become a line ...

However, now the dialog caption overlaps the oC logo and consumes quite a lot of space in height.

**Comment by guruz** [comment]
We have a 2.5 daily build (=testing quality) at http://download.owncloud.com/desktop/daily/ownCloud-2.5.0-daily20180328.MSVC.106.msi .. this has a new Qt version that might fix it.
Please note that 2.5 is unreleased to far, so use at your own risk!

**Comment by ogoffart** [comment]
It looks ok in my test in a VM.

Can someone try the 2.5 .msi build from http://download.owncloud.com/desktop/daily/ with highdpi and report problems ?

**Comment by guruz** [comment]
@martin-rueegg Do you want to try 2.5.0 alpha1? https://github.com/owncloud/client/releases

**Comment by guruz** [comment]
2.5.0 beta1 is out :-)
https://central.owncloud.org/t/desktop-sync-client-2-5-0-beta1-released/14667
Everyone, please comment here if we can close this issue. Thank you.

**Comment by michaelstingl** [comment]
Looks much better with todays 2.5.0 daily build:

<img width="860" alt="msedge_-_win10" src="https://user-images.githubusercontent.com/214010/43847242-6c92ea88-9b30-11e8-94f2-ec06b60a215c.png">
