### ISSUE TITLE
[Win] Client 2.1.0 floods log with "Access denied" messages for files set read-only attribute by manual user intervention

### ISSUE THREAD

**Issue by brozkeff** [owncloud/client#4308]
### Expected behaviour
I upload files via client 2.1.0 in Linux to folder shared read-only to a group, others using 2.1.0 client on Windows 7 download files and client does not complain at all

### Actual behaviour
I upload files on Linux Mint 17.2 Xfce via client 2.1.0 to my folder that is shared read-only to a group, others using 2.1.0 client on Windows 7 download files seemingly OK but client complains with a red cross and log is flooded with repeated messages stating stat for some of such files, "Access denied". 
On Friday I upgraded the Windows clients to 2.1.0, I don't remember when I upgraded my Linux machine to 2.1.0, but on previous client versions on Windows such error messages were non-existent. Files created on Windows and shared to other users seem to be OK but the other folders where people share files are writable also by the other users, the "GRAFIKA MM" is perhaps the only folder (owned by me, being written from Linux) that I share with others read-only.

### Steps to reproduce
1. upload files via Linux client 2.1.0 to group-shared folder that the group has read-only
2. let another member of the group using Windows client 2.1.0 download such files (the client is runnning while the Linux uploads and re-uploads the files)
3. observe the owncloud client log and icon, probably some files will show in the Activity tab as "non-synced" with the "Access denied" message,. while at the same time the file seems to be downloaded correctly to the local folders and in the "sync protocol" the file is shown as Downloaded

### Server configuration
Operating system: Ubuntu server 14.04

Web server: Apache 2.4.7

Database: MySQL 5.5.46

PHP version: 5.5.9

ownCloud version: 7.0.11

Storage backend: local filesystem

### Client configuration - who uploaded files
Client version: 2.1.0, git c0c9fb, Dec 3 2015, 15:29:46, Qt 4.8.6, ,OpenSSL 1.0.1f 6 Jan 2014

Operating system: Linux Mint 17.2 Xfce, kernel 4.2.0-19-generic amd64

OS language: Czech

Installation path of client: default (apt package)

### Client configuration - who downloaded files
Client version: 2.1.0

Operating system: Windows 7 SP1 64bit

OS language: Czech

Installation path of client: default (exe installation package)

### Logs

Log fragment from Linux client where I uploaded some files on Friday (Odesláno = Sent):

```text
18.12.15 14:14:05GRAFIKA MM/ESHOP/slidery/dobryvanocnitrh-sk_2015.jpg            TierraVerde                   Odesláno       93 KB     
18.12.15 14:13:57GRAFIKA MM/ESHOP/slidery/dobryvanocnitrh-sk_2015.xcf            TierraVerde                   Odesláno       211 KB    
18.12.15 14:08:59MARKETING/_MAILING/NEWSLETTER/mailing2015_12_sk.html            TierraVerde                   Odesláno       6,1 KB    
18.12.15 14:06:52GRAFIKA MM/ESHOP/slidery/expedice_vanoce2015sk.jpg              TierraVerde                   Odesláno       86 KB     
18.12.15 14:04:40GRAFIKA MM/ESHOP/slidery/expedice_vanoce2015en.jpg              TierraVerde                   Odesláno       51 KB     
18.12.15 14:04:26GRAFIKA MM/ESHOP/slidery/expedice_vanoce2015.xcf                TierraVerde                   Odesláno       124 KB    
18.12.15 13:59:34GRAFIKA MM/ESHOP/slidery/expedice_vanoce2015sk.jpg              TierraVerde                   Odesláno       86 KB     
18.12.15 13:59:21GRAFIKA MM/ESHOP/slidery/expedice_vanoce2015cz.jpg              TierraVerde                   Odesláno       82 KB     
18.12.15 13:59:09GRAFIKA MM/ESHOP/slidery/expedice_vanoce2015cz.png              TierraVerde                   Odesláno       80 KB     
18.12.15 13:57:06GRAFIKA MM/ESHOP/slidery/expedice_vanoce2015.xcf                TierraVerde                   Odesláno       81 KB
```

Files are in a shared folder that other users have read-only. Windows clients seem to download all files correctly but a red cross is on the icon of client and log is flooded with messages for some of these files (Přístup byl odepřen = Access denied):

```text
21.12.2015 7:44:49GRAFIKA MM/ESHOP/slidery/expedice_vanoce2015sk.jpg              D:\RS\Documents\TIERRA VERDE  Přístup byl odepřen.
21.12.2015 7:44:49GRAFIKA MM/ESHOP/slidery/expedice_vanoce2015.xcf                D:\RS\Documents\TIERRA VERDE  Přístup byl odepřen.
21.12.2015 7:44:49GRAFIKA MM/ESHOP/slidery/dobryvanocnitrh-sk_2015.xcf            D:\RS\Documents\TIERRA VERDE  Přístup byl odepřen.
21.12.2015 7:44:49GRAFIKA MM/ESHOP/slidery/dobryvanocnitrh-sk_2015.jpg            D:\RS\Documents\TIERRA VERDE  Přístup byl odepřen.
```
(...repeating ad infinitum)

2. Web server error log:

No idea if this may be related, but nothing else in errorlog is present.

```text
[Fri Dec 18 16:35:20.394649 2015] [:error] [pid 9317] [client 81.19.3.71:64500] PHP Warning:  apc_store(): GC cache entry 'oc1fdcd11858/AutoloaderOCA\\Files_Trashbin\\Trashbin' was on gc-list for 4524 seconds in /var/www/owncloud/lib/private/memcache/apc.php on line 21
[Fri Dec 18 16:35:20.613733 2015] [:error] [pid 9317] [client 81.19.3.71:64500] PHP Warning:  apc_store(): GC cache entry 'oc1fdcd11858/AutoloaderDoctrine\\DBAL\\Driver\\PDOConnection' was on gc-list for 4524 seconds in /var/www/owncloud/lib/private/memcache/apc.php on line 21
[Fri Dec 18 16:35:20.613781 2015] [:error] [pid 9317] [client 81.19.3.71:64500] PHP Warning:  apc_store(): GC cache entry 'oc1fdcd11858/AutoloaderDoctrine\\DBAL\\Configuration' was on gc-list for 4524 seconds in /var/www/owncloud/lib/private/memcache/apc.php on line 21
[Fri Dec 18 16:35:20.613808 2015] [:error] [pid 9317] [client 81.19.3.71:64500] PHP Warning:  apc_store(): GC cache entry 'oc1fdcd11858/AutoloaderOC\\AppConfig' was on gc-list for 4524 seconds in /var/www/owncloud/lib/private/memcache/apc.php on line 21
[Fri Dec 18 16:35:20.613833 2015] [:error] [pid 9317] [client 81.19.3.71:64500] PHP Warning:  apc_store(): GC cache entry 'oc1fdcd11858/AutoloaderOC\\Files\\Stream\\OC' was on gc-list for 4524 seconds in /var/www/owncloud/lib/private/memcache/apc.php on line 21
[Fri Dec 18 16:35:20.613861 2015] [:error] [pid 9317] [client 81.19.3.71:64500] PHP Warning:  apc_store(): GC cache entry 'oc1fdcd11858/AutoloaderOC\\Log\\ErrorHandler' was on gc-list for 4524 seconds in /var/www/owncloud/lib/private/memcache/apc.php on line 21
[Fri Dec 18 16:35:20.613885 2015] [:error] [pid 9317] [client 81.19.3.71:64500] PHP Warning:  apc_store(): GC cache entry 'oc1fdcd11858/AutoloaderOC_Util' was on gc-list for 4524 seconds in /var/www/owncloud/lib/private/memcache/apc.php on line 21
[Fri Dec 18 21:49:07.312207 2015] [:error] [pid 13423] [client 82.117.159.151:52627] PHP Warning:  apc_store(): GC cache entry 'oc1fdcd11858/AutoloaderDoctrine\\DBAL\\DriverManager' was on gc-list for 3606 seconds in /var/www/owncloud/lib/private/memcache/apc.php on line
 21
[Fri Dec 18 21:49:07.313228 2015] [:error] [pid 13423] [client 82.117.159.151:52627] PHP Warning:  apc_store(): GC cache entry 'oc1fdcd11858/AutoloaderOC_Util' was on gc-list for 3606 seconds in /var/www/owncloud/lib/private/memcache/apc.php on line 21
```

3. ownCloud log (data/owncloud.log):

The only records related to these files seem to be triggered by the preview app.

```{"reqId":"56740336b6bb5","app":"core","message":"No preview providers exist","level":3,"time":"December 18, 2015 13:59:34","method":"PUT","url":"\/remote.php\/webdav\/GRAFIKA%20MM\/ESHOP\/slidery\/expedice_vanoce2015sk.jpg"}
{"reqId":"56740336b6bb5","app":"hook","message":"error while running hook (OC\\Preview::post_write): No preview providers","level":3,"time":"December 18, 2015 13:59:34","method":"PUT","url":"\/remote.php\/webdav\/GRAFIKA%20MM\/ESHOP\/slidery\/expedice_vanoce2015sk.jpg"}
{"reqId":"5674045b2ecdb","app":"core","message":"No preview providers exist","level":3,"time":"December 18, 2015 14:04:27","method":"PUT","url":"\/remote.php\/webdav\/GRAFIKA%20MM\/ESHOP\/slidery\/expedice_vanoce2015.xcf"}
{"reqId":"5674045b2ecdb","app":"hook","message":"error while running hook (OC\\Preview::post_write): No preview providers","level":3,"time":"December 18, 2015 14:04:27","method":"PUT","url":"\/remote.php\/webdav\/GRAFIKA%20MM\/ESHOP\/slidery\/expedice_vanoce2015.xcf"}
{"reqId":"567404689fd28","app":"core","message":"No preview providers exist","level":3,"time":"December 18, 2015 14:04:40","method":"PUT","url":"\/remote.php\/webdav\/GRAFIKA%20MM\/ESHOP\/slidery\/expedice_vanoce2015en.jpg"}
{"reqId":"567404689fd28","app":"hook","message":"error while running hook (OC\\Preview::post_write): No preview providers","level":3,"time":"December 18, 2015 14:04:40","method":"PUT","url":"\/remote.php\/webdav\/GRAFIKA%20MM\/ESHOP\/slidery\/expedice_vanoce2015en.jpg"}
{"reqId":"567404ed1c1ee","app":"core","message":"No preview providers exist","level":3,"time":"December 18, 2015 14:06:53","method":"PUT","url":"\/remote.php\/webdav\/GRAFIKA%20MM\/ESHOP\/slidery\/expedice_vanoce2015sk.jpg"}
{"reqId":"567404ed1c1ee","app":"hook","message":"error while running hook (OC\\Preview::post_write): No preview providers","level":3,"time":"December 18, 2015 14:06:53","method":"PUT","url":"\/remote.php\/webdav\/GRAFIKA%20MM\/ESHOP\/slidery\/expedice_vanoce2015sk.jpg"}```

**Comment by guruz** [comment]
> ownCloud version: 7.0.11

Current server is 8.2.x

FYI @PVince81

**Comment by brozkeff** [comment]
Yes the production is still OC 7. The client 2.1.0 is marked as incompatible with that "vintage" version of server? Perhaps the client should be aware of feature limitations of the server it communicates with, it the client tries to send some unsupported metadata or whatever else.

I *am* testing 8.2 on a cloned VPS but due to the amount of data and complex sharing, re-sharing, read-write, read-only permission structure we have, I am conservative when it comes to upgrading to new major versions on the server, mostly due to bugs such as https://github.com/owncloud/core/issues/20769 that until now would cause a nightmare if triggered on the production data. Hopefully once 8.2.2 is considered stable and this particular bug is really fixed I plan to do upgrade. Testing 8.2.2-rc1 already seems the data loss does not occur so hopefully the big upgrade will be performed as soon as final 8.2.2 is available in the repositories.

**Comment by MiragePV** [comment]
I am using OC 8.2 on a server, and users have Windows 7 clients 2.1.0.

Scenario:
Admin creates a file, sets read-only attribute for a user (share and edit checkboxes unticked).
Client downloads/syncs a file. The file has Windows read-only attribute set.
Admin edits the file.
Client gets an error message 'access denied' when trying to sync the file. (because it's read only, obviously). Client is unable to edit the file whatsoever as long as he doesn't untick to read-only attribute in file properties (which would be completely nuts to do this after every sync)
This only happens with 2.1.0 client. Older client (2.0.2) didn't set the read-only attribute to the file itself.

So I guess it's not the issue of having an older version of OC, but of having the 2.1.0 client.
Fix soon?

**Comment by brozkeff** [comment]
If the new client really sets the read-only file attribute to all files shared read-only, to prevent editing (and this is the desired behaviour), then certainly the only sensible thing is to 
a) un-set this permission before attempting to change this file when changes on the server are to be propagated to the locally synced file,
b) re-download the changed file,
c) re-set the read-only attribute.
This does not have to be done every sync, because not every sync there are changes to all the read-only files - most of the time no change occurs, sometimes few files are changed etc.

I hope the mechamism in the client contains also the feature to disable read-only attributes to all files if at any time the owner of the files or the one who shared them adds writable permissions as well.

**Comment by brozkeff** [comment]
@MiragePV Your scenario contains only Windows users sharing files between each other? If so, then we should change the title of this issue, because it is not specific for Linux on the side of the one who shares files, and if the same happens on server 8.2, also the "Server involved" tag should be removed. It seems this whole behaviour requires only (a) Client 2.1.0, (b) setting some shared folder and files read-only, and (c) changing such files or adding new ones by the owner and propagating them to the users' synced folders where the read-only attributes are already set.

**Comment by MiragePV** [comment]
@brozkeff Yes, it's basically as you said. In my scenario all users run Windows (7/8/10). IMO the problem isn't Linux specific or server related, it is just (probably) new Windows client setting attribute which it shouldn't. Older version didn't set the read-only attribute at all.
Generally, setting the read-only attribute is stupid since user can modify the file on his own machine (by removing read-only manually), but he still wouldn't be able to send it to the cloud, rather error message would occur that the user doesn't have 'write' perrmision (which is expected behavior).

To your previous post: I am not sure such feature exists or is working correctly. Once you download a read-only file, you can't do anything with it unless you manually untick the attribute.

**Comment by brozkeff** [comment]
@MiragePV Moreover by setting read-only attribute to folder does not disable the user to create NEW files inside that folder which cannot be synced back to server anyway so the new behaviour of the client solves just part of the read-only problem (and creates new problems).
I would consider either reverting back to the old functionality (not setting any read-only attributes and removing all of them during upgrade), or to improve the read-only functionality that at least it temporarily disables the attribute to re-download a changed version.
Because most regular users don't even know what a read-only attribute is, and such attributes remain on the files also on copying/moving them anywhere else for doing local edits, this new behaviour seems to me as undesired and user-unfriendly.
Making files and folders shared read-only via owncloud as read-only on the operating system level would be nice but I am afraid there is no way how to achieve it properly. Perhaps ownCloud client should be more proactive and display more suggestive error messages if it detects that the user placed some new files or changed some existing files in a folder he has read-only on ownCloud.
An OSD bubble from the toolbar icon could read something as

//"It seems you added file xxx.doc to the ownCloud folder "GRAPHICS" that user "owncloudadmin" shared to you as read-only. Your changes cannot be saved back to this folder on the server. Should I move your files to "GRAPHICS-local" folder and restore the original versions in the shared folder? [Yes] [later...]"//

(The YES should be the default, while for keeping it inconsistent should be avoided as much as possible, so there should be no option "NO and keep it this way forever" but rather only "later" (on clicking this there should be guide to save all opened and changed files and offer asking again in a few minutes)

**Comment by ckamm** [comment]
The analysis so far is correct: The new Windows client sets the read-only flag on files that the server deems read-only. This causes problems with deletes and updates sometimes because it also prevents the client from changing the file.

For deletes, this was already addressed by @ogoffart in 11174ddf4cb3283548dd0fa13ca5c45a02c3e224. I'll go through other propagation jobs and check for similar issues.

**Comment by ckamm** [comment]
@brozkeff @MiragePV There's a good chance the problem is already fixed in the nightlies, could you give them a shot? http://download.owncloud.com/desktop/daily/

**Comment by ckamm** [comment]
@brozkeff @MiragePV Actually, no, there are more issues.

**Comment by ckamm** [comment]
@brozkeff @MiragePV The 5750 build from http://download.owncloud.com/desktop/daily/ has the latest change and should hopefully behave much better.

**Comment by brozkeff** [comment]
@ckamm: I tested the 5750 build on one of our affected Win7 computers. Results:
- Good news, Deleted files on the server were finally sucessfully deleted also on the computer where user had read-only access to the folder structure
- Not yet solved by the client itself: the client still reported Access denied to all other files that were "just" changed, the folders and files were still having read-only attribute on the filesystem level. Workaround that worked: I closed the client, and recursively disabled the read-only attribute to this whole folder structure, after starting the client again all changes were finally sucessfully propagated to the local filesystem and the long-awaited green check reappeared again.

So the mess created by 2.1.0 (read-only files and folders on the filesystem level) is still not perfectly resolved by the 5750 build unless I manually remove the readonly attribute whe the client is closed.

Note that the user I tested the client doesn't have administrator privileges in Windows7, for updating the client I must always enter administrator password.

**Comment by ckamm** [comment]
@brozkeff Could you elaborate on the remaining problems? Deletions and updates of files in read-only shares now work correctly for me on Windows and I don't see any 'Access Denied' messages in the log.

Making files in read-only shares read-only on the filesystem was added intentionally to 2.1.0. Any changes to the files will be discarded on the next sync and we think it's a good idea to hint at that by making the files read-only.

> Because most regular users don't even know what a read-only attribute is, and such attributes remain on the files also on copying/moving them anywhere else for doing local edits, this new behaviour seems to me as undesired and user-unfriendly.

It's indeed unfortunate that copying preserves the read-only attribute. @dragotin

**Comment by brozkeff** [comment]
Great news everybody!

I installed the latest daily build ownCloud-2.1.1.5762-nightly20160111-setup.exe to one of our affected Win7 machines that had 2.1.0, and both issues ((a) deleting files that were removed by the owner and showing this in the log) and (b) the access-denied messages for altered files are gone, with green check appearing without any need to tweak file attributes manually or to do any other intervention.

I did not test it on any other platforms so only 2.1.0 -> 2.1.1.5762-nightly20160111 on Windows 7 is confirmed to fix this issue.

Looking forward for 2.1.1 to be released soon so all affected 2.1.0 clients would be offered auto-update which will magically solve the problems :)

BTW - will the daily builds auto-update to the stable 2.1.1 once it is released and stay on the stable branch or do I need to manually upgrade these two computers with the daily builds once the stable build is ready?

**Comment by danimo** [comment]
@brozkeff The daily builds will also upgrade to the next stable build once available.

**Comment by brozkeff** [comment]
@danimo Great!

**Comment by ckamm** [comment]
@brozkeff Thanks for testing! :)
