### ISSUE TITLE
Branding option wizardSelectiveSyncDefaultNothing  not working as expected

### ISSUE THREAD

**Issue by rperezb** [owncloud/client#4581]
### STEPS:

No matter the option set on: 
`bool wizardSelectiveSyncDefaultNothing () const { return true; }``

No matter what i set false/ true but the selective sync is always checked everything
### EXPECTED:

When true, the setup wizard will show the selective sync dialog by default and default to nothing selected, ie. nothing to be selected for syncing.

Related to: https://github.com/owncloud/ownbrander/issues/424#issuecomment-197934679

**Comment by ckamm** [comment]
@rperezb I merged a patch that makes it work for me into master. Please test!

**Comment by rperezb** [comment]
- bool wizardSelectiveSyncDefaultNothing () const { return true; } -> nothing selected by default
- bool wizardSelectiveSyncDefaultNothing () const { return false; } -> everything selected by default

**Comment by rperezb** [comment]
thx, @ckamm working fine

**Comment by SamuAlfageme** [comment]
Reopening this as there's one use case where the bug is still present because of the differences between the add account and add folder sync connection wizards.

This condition can be tested with testpilotcloud as it has this option set by default.

 ### Steps to reproduce:
1. Create a new account
2. `Skip folders configuration` 
3. `Add Folder Sync Connection` and select any folder.

### Current behavior 
All the subfolders of the parent selected in **3** appear as checked in the `Choose What to Sync` view.

### Expected behavior 
The same than in the new account wizard; all the subfolders appear unchecked:

![choose](https://cloud.githubusercontent.com/assets/2644445/21500415/fa042fb6-cc3e-11e6-8cb5-2df170bf4814.png)

**Comment by SamuAlfageme** [comment]
Also, noticed the `Choose what to sync` button to have a different appearance when the subfolder selection dialog is opened automatically:

![screenshot 2016-12-27 14 19 44](https://cloud.githubusercontent.com/assets/2644445/21500485/8f446c44-cc3f-11e6-98b8-1102bbc9d43d.png)

**Comment by ckamm** [comment]
I'll check this out.

**Comment by ckamm** [comment]
This fix depends on other work and has been added to pull request #5426

**Comment by SamuAlfageme** [comment]
👍 closing here as well waiting for PR #5426 to merge. 

As for https://github.com/owncloud/client/issues/4581#issuecomment-270367437 I'm figuring out a test plan for all the theming options, to see if there's any more details like this.
