### ISSUE TITLE
[Linux] Owncloud client 2.2.1: localization is broken

### ISSUE THREAD

**Issue by ls960** [owncloud/client#4956]
After upgrading from 2.2.0 language is english instead of italian.

**Comment by guruz** [comment]
Which OS?

**Comment by Kaor** [comment]
same for me, on ubuntu 14.04 64bits

**Comment by danimo** [comment]
do you have `owncloud-client-l10n` installed?

**Comment by ls960** [comment]
Yes @danimo , it'installed

**Comment by danimo** [comment]
ah, but it's empty, I see.. @jnweiger:

```
$ dpkg -L owncloud-client-l10n
/.
/usr
/usr/share
/usr/share/owncloud
/usr/share/owncloud/i18n
/usr/share/doc
/usr/share/doc/owncloud-client-l10n
/usr/share/doc/owncloud-client-l10n/copyright
/usr/share/doc/owncloud-client-l10n/changelog.Debian.gz
```

**Comment by jnweiger** [comment]
yup.... a fix that did not make it into the templates automatically turns into a regression.
Fixed applied to in https://build.opensuse.org/package/show/isv:ownCloud:community:testing/owncloud-client

**Comment by jnweiger** [comment]
owncloud-client-l10n for Ubuntu-16.04 from :testing now contains this:
<pre>
du -a ~/tmp/l10n/
4	/DEBIAN/control
12	/DEBIAN
104	/usr/share/owncloud/i18n/client_cs.qm
28	/usr/share/owncloud/i18n/client_TW.qm
108	/usr/share/owncloud/i18n/client_pt_BR.qm
96	/usr/share/owncloud/i18n/client_sl.qm
104	/usr/share/owncloud/i18n/client_nl.qm
60	/usr/share/owncloud/i18n/client_eu.qm
80	/usr/share/owncloud/i18n/client_ja.qm
108	/usr/share/owncloud/i18n/client_it.qm
80	/usr/share/owncloud/i18n/client_fi.qm
40	/usr/share/owncloud/i18n/client_fa.qm
76	/usr/share/owncloud/i18n/client_uk.qm
112	/usr/share/owncloud/i18n/client_de.qm
68	/usr/share/owncloud/i18n/client_et.qm
84	/usr/share/owncloud/i18n/client_pl.qm
108	/usr/share/owncloud/i18n/client_pt.qm
96	/usr/share/owncloud/i18n/client_sv.qm
108	/usr/share/owncloud/i18n/client_ru.qm
64	/usr/share/owncloud/i18n/client_zh_TW.qm
96	/usr/share/owncloud/i18n/client_el.qm
112	/usr/share/owncloud/i18n/client_fr.qm
72	/usr/share/owncloud/i18n/client_zh_CN.qm
64	/usr/share/owncloud/i18n/client_hu.qm
92	/usr/share/owncloud/i18n/client_th.qm
108	/usr/share/owncloud/i18n/client_es.qm
76	/usr/share/owncloud/i18n/client_sr.qm
44	/usr/share/owncloud/i18n/client_es_AR.qm
76	/usr/share/owncloud/i18n/client_gl.qm
84	/usr/share/owncloud/i18n/client_ca.qm
4	/usr/share/owncloud/i18n/client_en.qm
96	/usr/share/owncloud/i18n/client_tr.qm
96	/usr/share/owncloud/i18n/client_nb_NO.qm
76	/usr/share/owncloud/i18n/client_sk.qm
2624	/usr/share/owncloud/i18n
2628	/usr/share/owncloud
4	/usr/share/doc/owncloud-client-l10n/changelog.Debian.gz
4	/usr/share/doc/owncloud-client-l10n/copyright
12	/usr/share/doc/owncloud-client-l10n
16	/usr/share/doc
2648	/usr/share
2652	/usr
2668	/
</pre>

**Comment by danimo** [comment]
desktop now only has `client_en.qm`

**Comment by nazar-pc** [comment]
2.2.1~nightly2016617-1.1 still doesn't have any translations inside

**Comment by ls960** [comment]
Today's upgrade to 2.2.2-1.1 on xubuntu 16.04 is still without translation.

**Comment by tmysik** [comment]
I can confirm that version 2.2.2 is a bit better, it contains now l10n for (only) English :)

```
# dpkg -l owncloud-client-l10n
=======================================================================
ii  owncloud-client-l10n              2.2.2-1.1             all                   Internationalization files for ownCloud
```
```
# dpkg -L owncloud-client-l10n 
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/owncloud-client-l10n
/usr/share/doc/owncloud-client-l10n/copyright
/usr/share/doc/owncloud-client-l10n/changelog.Debian.gz
/usr/share/owncloud
/usr/share/owncloud/i18n
/usr/share/owncloud/i18n/client_en.qm
```

**Comment by jnweiger** [comment]
related https://github.com/owncloud/client/issues/4987

**Comment by jnweiger** [comment]
related https://github.com/owncloud/client/issues/4987
