### ISSUE TITLE
Qt-5.6.2 everywhere

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#5470]
Public client builds
* [x] Windows https://github.com/owncloud/client/issues/3449
* [x] Mac https://github.com/owncloud/client/issues/3449
* [x] Linux clients should all use the same Qt version: 5.6.2

**Comment by jnweiger** [comment]
@SamuAlfageme https://github.com/owncloud/client/issues/2558#issuecomment-99424884 lists many issues we identified in qt-5.5.1, and older versions (including qt4)
Can you please design a test suite to cover all these issues? This helps to demonstrate that qt-5.6.2 is a good choice.

**Comment by jnweiger** [comment]
@guruz https://github.com/owncloud/client/issues/3449 mentions patches. Are these obsolete with 5.6.2?

**Comment by guruz** [comment]
@jnweiger Yes, no patches needed

**Comment by moscicki** [comment]
Please also remember to take on board this comment: https://github.com/owncloud/client/issues/2558#issuecomment-75262413

Or shall I open another issue for it?

**Comment by guruz** [comment]
What's the status on this? People in https://github.com/owncloud/client/issues/4828 are waiting for it..

**Comment by jnweiger** [comment]
We have set up a devel project in obs for providing Qt-5.6.2 packages for the Linux platforms. https://build.opensuse.org/package/show/isv:ownCloud:devel:Qt562/qt5-qtbase

The plan is:
* [ ] collect all needed packages there
* [ ] define the list of Linux build targets.
* [ ] make these packages build on all targets.
** [ ] SUSE rpms, [ ] Fedora rpms, [ ] centOS rpms
** [ ] Ubuntu DEB packages, [ ] Debian DEB packages.
* [ ] change the packages to install without conflicting with existing system qt packages
* [ ] change the packages to allow proper requires/provides
* [ ] test build with owncloud-client-2.2.4 and 2.3.0

**Comment by jnweiger** [comment]
Qt-5.6.2 completion will not be ready for 2.3.0
the packaging roadmap for the 2.3.0 release are

* [ ] Roll back 2.2.4 in the testing project to using the Qt4/Qt5 packages from the distributions.
* [ ] Test by comparing with 2.2.3 packages that the rollback is complete and without regressions.
* [ ] Re-Release 2.2.4 packages 
* [ ] create 2.3.0 setup in the testing project using the Qt4/Qt5 packages from the distributions.
* [ ] Release 2.3.0 packages.
* [ ] Push the Qt-5.6.2 setup from devel:Qt562 to the testing project and make that work with 2.3.0 code base.
* [ ] Prepare beta-testing of the combination 2.3.0 with 5.6.2 -- suggest to use testpilotcloud-client for this.
* [ ] Release 2.3.1 with 5.6.2

**Comment by vladimiroff** [comment]
>  test the 2.3.0 setup in the testing project using the Qt4/Qt5 packages from the distributions.

So, in summary Qt4 support is not being dropped, before 2.3.1.

Do you have a list of which distributions have issues with Qt 5.x packages and therefore need a Qt 4.x build of the client? I'm also interested in what is exactly the Qt 4.x version there.

**Comment by jnweiger** [comment]
@SamuAlfageme We have an original 2.2.4 build unchanged from release time in https://software.opensuse.org/download.html?project=isv%3AownCloud%3Acommunity%3Atesting&package=testpilotcloud-client -- I've disabled rebuilds there for now, so that we don't lose this as a reference. Copying to https://software.opensuse.org/download.html?project=isv%3AownCloud%3Acommunity%3Atesting%3Atestpilotcloud-client-2.2.4-20160927&package=testpilotcloud-client for persistent reference.

**Comment by SamuAlfageme** [comment]
@jnweiger current [testpilot](http://download.opensuse.org/repositories/isv:/ownCloud:/testpilot/) also works as a more updated reference for the comparison. 

The most notable changes between that repository and the current (If we limit to main client package dependencies)... 

```diff
Package: 
< testpilotcloud-client
> owncloud-client
Version: 
< 2.2.4-1.2
> 2.2.4-9.1
Installed-Size:
< 2241
> 2538
Depends: libc6 (>= 2.14), libgcc1 (>= 1:3.0), 
< libqt5core5a (>= 5.5.0),
> libowncloudsync0 (= 2.2.4-9.1), libqt5core5a (>= 5.6.0~beta),
libqt5dbus5 (>= 5.0.2), libqt5gui5 (>= 5.0.2) | libqt5gui5-gles (>= 5.0.2), libqt5keychain1, libqt5network5 (>= 5.0.2), 
< libqt5webkit5 (>= 5.0.2), 
> libqt5webkit5 (>= 5.6.0~rc),
libqt5widgets5 (>= 5.2.0), libqt5xml5 (>= 5.0.2), libssl1.0.0 (>= 1.0.0), libstdc++6 (>= 5.2), 
< libtestpilotcloudsync0 (= 2.2.4-1.2), testpilotcloud-client-l10n,
> owncloud-client-l10n,
libqt4-sql-sqlite | libqt5sql5-sqlite
Filename: 
< ./amd64/testpilotcloud-client_2.2.4-1.2_amd64.deb
> ./amd64/owncloud-client_2.2.4-9.1_amd64.deb
Size: 
< 763094
> 977198
```

... would be the version of qt core (which switched to v5.6.0~beta) and webkit libraries. I'll peek some more into changes for those repositories and keep posting here.

**Comment by SamuAlfageme** [comment]
So, ran the scripts (plus the https://github.com/lvc/pkgdiff utility) and main differences reported between our two references still (as in my previous https://github.com/owncloud/client/issues/5470#issuecomment-276320318) reside in the DEB packages (both Ubuntu and Debian packages) they also were the main source of the problems reported with the tray icons. On rpms I'm seeing they uniformly use `qtbase5.4.2`.

**Comment by jnweiger** [comment]
Qt-5.6.2 for Debian-7.0 has a number of missing dependencies that are present on Debian_8.0 and all Ubuntu's : 
<pre>
nothing provides libgstreamer-plugins-base1.0-dev, 
nothing provides libgstreamer1.0-dev, 
nothing provides libxcb-sync-dev, 
nothing provides libxcb-xkb-dev, 
nothing provides libxkbcommon-dev, 
nothing provides libxkbcommon-x11-dev, 
nothing provides qttools5-dev-tools, 
nothing provides libqt5sql5-sqlite
</pre>

**Comment by jnweiger** [comment]
Rollbacks done:
* templates https://github.com/owncloud/administration/commit/67aac508de532564afeeca4e0f6f3ed062134ff7
* 2.2.4-2 https://build.opensuse.org/package/show/isv:ownCloud:desktop/owncloud-client 2.2.4-2 pending QA, unpublished re-release candidate.
* 2.3.0~pre1-2 https://build.opensuse.org/package/show/isv:ownCloud:community:testing/owncloud-client pending QA, public release candidate

fyi @guruz @michaelstingl (prepare a re-release announcement?)

**Comment by michaelstingl** [comment]
> prepare a re-release announcement?

@jnweiger what do you mean?

**Comment by dschmidt** [comment]
@jnweiger xkbcommon is not available on CentOS either, but Qt also bundles it, we can simply take that - or any reason not to? Not sure about xcb, but it might be bundled as well
Maybe check upstream backport patches how they resolve it?

FYI: Fedora and openSUSE builds are good to be tested, I'm currently working on CentOS 6 and 7 support

**Comment by dschmidt** [comment]
CentOS 7 package is ready, CentOS 6 has all dependencies ready but we currently can't build the client on that platform because the client uses C++ features (in the Qt5 build at least) that the ancient GCC 4.4 on CentOS 6 can't compile. We need to discuss and figure out what to do here...

**Comment by SamuAlfageme** [comment]
@jnweiger what a variety of versions! Reports of [installations](https://github.com/owncloud/platform/issues/81#issuecomment-277640258 ) of `.deb` packages now show this data, I don't really if everything is as expected: 
* Ubuntu 14.04 - `libqtcore4 amd64 4.8.5`
* **Ubuntu 16.04 - `libqt5core5a:amd64 5.5.1`**
* Ubuntu 16.10 - `libqtcore4 amd64 4.8.7`

As for the `rpm`'s the panorama is this: (cc/ @dschmidt)
* Centos 7: `opt-qt5-qtbase.x86_64 0:5.4.2`
* OpenSUSE Leap 42.2: `libQt5Core5-5.6.1` 
* Fedora 25: `qt5-qtbase.x86_64 5.7.1`

**Comment by michaelstingl** [comment]
@SamuAlfageme Having old stuff with **16.10** and newer stuff with **16.04** is also what I found confusing in https://github.com/owncloud/enterprise/issues/1634.

**Comment by jnweiger** [comment]
[x]  collect all needed packages there
collected in https://build.opensuse.org/project/show/isv:ownCloud:devel:Qt562

Also linkpack'ed into internal build service: https://obs.int.owncloud.com/project/show/devel:Qt562
CAUTION: prjconf must be manually propagated into internal OBS upon every change. No linking possible.

Both, RPM and DEB packages are built with variables defined in prjconf:
<pre>
%define _oc_pkg_name_client owncloud-client
%define _oc_client_executable owncloud
%define _oc_pkg_prefix oc
%define _oc_vendordir ownCloud
%define _oc_rootdir Qt-5.6.2
%define _oc_prefix /opt/ownCloud/Qt-5.6.2
</pre>
For DEB packages the variables are substituted into *.control *.dsc *.rules files manually by running make before checkin. 

For RPM the variables autoexpand during the build process, but now the dependency resolution became unreliable. See  https://github.com/openSUSE/open-build-service/issues/2665

**Comment by jnweiger** [comment]
Status update. @SamuAlfageme @dschmidt please correct me if I am wrong.
* openSUSE and Fedora RPMs are ready for testing.
* centOS toolchain (compiler and libraries) ready. owncloud-client WIP.
* DEB libraries successfully imported. Relocation into /opt/ WIP.

**Comment by dschmidt** [comment]
@jnweiger AFAICT owncloud-client is ready to test too, there were just issues with build service mirrors today. Downloading manually and doing `yum localinstall` just worked. Keyboard and network issues seem fixed now.

**Comment by michaelstingl** [comment]
@jnweiger @dschmidt @SamuAlfageme Awesome work? Do we already have something to test for the testpilots community?

**Comment by jnweiger** [comment]
@michaelstingl https://software.opensuse.org/download.html?project=isv%3AownCloud%3Adevel%3AQt562&package=owncloud-client
offers CentOS, Fedora, and openSUSE builds of owncloud-client 2.3.0~beta1 with our new Qt-5.6.2 libraries.

**Comment by SamuAlfageme** [comment]
@michaelstingl @dschmidt @jnweiger you can check the result of those installations in [this pipeline](https://gitlab.com/alfageme/client-linux-tests/pipelines/6463767), including installation sizes, etc. I can easily extend them to include Fedora 24, Centos 6 and OpenSUSE 42.1/13.2 if it's relevant for this too.

**Comment by dschmidt** [comment]
To keep everyone up to date:
@jnweiger did a great job of making `qt5-qtbase` for DEB based distributions. It apparently still has issues, but at least it builds, which is great progress. I'm picking up his work from there now.

**Comment by dschmidt** [comment]
I have `qttools` and `qtkeychain` building locally, unfortunately the OBS somehow seems to behave a little differently and the builds fail in the verification step. Should be minor issues only - but nothing for tonight anymore. 

`qt5-webkit` is almost building locally, again verification fails. This is hopefully the last package missing for being able to build the client itself. (When commenting out the webkit depedency there, the build starts).

One issue that I don't understand yet, is an unresolvable dependency on `qtchooser` on everything but Ubuntu 16.10.  Haven't spent much time on that yet though.

So overall there is quite a bit todo still, but we're making good progress. I'm in a constant feedback loop with @jnweiger, if anyone else can/wants to help out with anything, let me know. Everything I've done I have commited to the OBS. I'm hoping I will get to fixing a few more issues during the weekend.

**Comment by dschmidt** [comment]
We have working Qt packages on Ubuntu 16.10 64bit now, minor issues on other Ubuntu/Debian flavors still.
The actual client package needs some work still because we need to build Dolphin overlays with system Qt.

**Comment by jnweiger** [comment]
First build success for Ubuntu and Debian: all flavours have built an onwcloud-client package for the first time.
@SamuAlfageme do you want to try some of them?

I am installing owncloud-client from the Qt562 project for Ubuntu-14.04 like this:
<pre>
cat /etc/apt/sources.list.d/owncloud-client.list 
deb http://download.opensuse.org/repositories/isv:/ownCloud:/devel:/Qt562/xUbuntu_14.04/ /
sudo apt-get install owncloud-client
The following extra packages will be installed:
  libowncloudsync0 libxcb-xinerama0 oc-libqt5core5a oc-libqt5dbus5
  oc-libqt5gui5 oc-libqt5keychain1 oc-libqt5network5 oc-libqt5opengl5
  oc-libqt5printsupport5 oc-libqt5sql5 oc-libqt5webkit5 oc-libqt5widgets5
  oc-libqt5xml5 owncloud-client-l10n
Suggested packages:
  oc-libqt5libqgtk2 qt5-image-formats-plugins qtwayland5
Recommended packages:
  qttranslations5-l10n oc-libqt5svg5 oc-libqt5sql5-sqlite oc-libqt5sql5-mysql
  oc-libqt5sql5-odbc oc-libqt5sql5-psql
The following NEW packages will be installed:
  libowncloudsync0 libxcb-xinerama0 oc-libqt5core5a oc-libqt5dbus5
  oc-libqt5gui5 oc-libqt5keychain1 oc-libqt5network5 oc-libqt5opengl5
  oc-libqt5printsupport5 oc-libqt5sql5 oc-libqt5webkit5 oc-libqt5widgets5
  oc-libqt5xml5 owncloud-client owncloud-client-l10n
0 upgraded, 15 newly installed, 0 to remove and 230 not upgraded.
...
</pre> 

Notice all the oc-* packages for Qt, this is our rebuild of qt-5.6.2 that installs into /opt.
Currently this client does not install into the usual /usr/bin/owncloud location, instead, you have to call it as
<pre>
/opt/ownCloud/Qt-5.6.2/bin/owncloud
</pre>

It starts up fine and does some syncing already. the 'general' tab shows that we use QT-5.6.2 and bandwidth limiting is enabled in the 'network' tab. Great progress. Thank you @dschmidt for making this happen!
![230b1 qt562-u14 04](https://cloud.githubusercontent.com/assets/1108546/23593272/fd838098-020c-11e7-8bba-ca92ba5b4a09.png)

**Comment by dschmidt** [comment]
Actually `/usr/bin/owncloud` and `/usr/bin/owncloudcmd` should be available too. c.f. https://build.opensuse.org/package/view_file/isv:ownCloud:devel:Qt562/owncloud-client/debian.owncloud-client.install?expand=1

**Comment by dschmidt** [comment]
What worries me a little: `qt5-image-formats-plugins qtwayland5 qttranslations5-l10n` lack our prefix. Even if they are only suggested/recommended, we should investigate, why they are referenced at all.

**Comment by SamuAlfageme** [comment]
@jnweiger @dschmidt Awesome 🎉 I'll get get started today to run the sanity checks for Ubuntu to see how that goes!

**Comment by SamuAlfageme** [comment]
I'm getting unmet deps. for all the 3 Ubuntu versions:

```
The following packages have unmet dependencies:
 owncloud-client : Depends: libowncloudsync0 (= 2.3.0~beta1-1.2) but it is not going to be installed
                   Depends: owncloud-client-l10n but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by dschmidt** [comment]
I have commited a few (possible) fixes to the OBS, let's see :-)
Looking into it, I wonder why it worked for @jnweiger in the first place.

**Comment by guruz** [comment]
@dschmidt @SamuAlfageme Wanna post on https://central.owncloud.org/ and ask people to test the 2.3.0 client packages with 5.6.2 bundles?

**Comment by SamuAlfageme** [comment]
@guruz we could publish them as testpilotcloud to avoid interfering with current setups as @jnweiger suggested on https://github.com/owncloud/client/issues/5470#issuecomment-275680311. Also note that in the `Qt562` we currently have `2.3.0beta1`

**Comment by dschmidt** [comment]
Today I fixed some more minor issues with the debian packages, updated the tarball to current 2.3 branch (fixing #5610) and added `-dbg` packages. 
I chose the legacy `-dbg` format (instead of `-dbgsym`) as it's completely compatible between Debian and Ubuntu and also is fully supported by the OBS. If we wanted to use `-dbgsym`-`.ddeb` Files we probably need changes in OBS..

**Comment by jnweiger** [comment]
Today also most of the libraries succeeded for RHEL-7
https://build.opensuse.org/project/monitor/isv:ownCloud:devel:Qt562:rhel7-extra
This is still in a separate project, but should be simple to merge.

**Comment by michaelstingl** [comment]
:+1: power to the people! :+1:

**Comment by jnweiger** [comment]
Pushing my RHEL7 libraries from rhel7-extra into the main devel:Qt562 

* RHEL-6 almost there
* a c++11 compiler still missing for fancy owncloud-client syntax.

**Comment by jnweiger** [comment]
[    3s] ++ ./test-c++11
[    3s] + '[' 'Hello World' = 'Hello World' ']'
[    3s] + echo 'SUCCESS!'
[    3s] SUCCESS!
[    3s] + exit 0

**Comment by jnweiger** [comment]
![all-clients-562](https://cloud.githubusercontent.com/assets/1108546/24056797/5abb563c-0b45-11e7-8a42-9137f730eb88.png)

**Comment by michaelstingl** [comment]
Awesome job !!!

**Comment by michaelstingl** [comment]
Can we get a 2.3.1 rc2 with this?

@SamuAlfageme What do you think from qa perspective?

**Comment by SamuAlfageme** [comment]
@jnweiger just included Debian in the tests and everything is looking good and shiny 😎

Is it worth to test RHEL packages **on RHEL**? There's no Dockerimage because of the nature of the project so maybe it's valuable to perform the tests with the packages on CentOS / try out with an unofficial image: https://hub.docker.com/r/richxsl/rhel7/

I don't know though why the hermes feed (https://hermes.opensuse.org/feeds/79973.rdf) wasn't updated after last packages' build success 😕

**Comment by jnweiger** [comment]
Open for review:

* [ ] check distro patches for Qt5.6.2 e.g. unity integration. @jturcotte please help here.
* [ ] check visually for all platforms.
* [ ] feedback from alpha testers and nightly

**Comment by michaelstingl** [comment]
Next steps to make the progress testable:

- [ ] Upgrade OBS project with 2.3.1 ([project page](https://build.opensuse.org/project/show/isv:ownCloud:devel:Qt562), [download page](https://software.opensuse.org/download.html?project=isv%3AownCloud%3Adevel%3AQt562&package=owncloud-client))
- [ ] Build [nightlies](https://build.opensuse.org/package/show/isv:ownCloud:community:nightly/owncloud-client) with Qt-5.6.2
- [ ] Build [Testpilotclient](https://build.opensuse.org/package/show/isv:ownCloud:community:nightly/testpilotcloud-client) with Qt-5.6.2

**Comment by michaelstingl** [comment]
@jnweiger Can we add @ogoffart 's patches to the Linux builds too? (see https://github.com/owncloud/client/issues/5618)

**Comment by jnweiger** [comment]
3.2.1 tar copied pushed into Qt526

**Comment by jnweiger** [comment]
Testpilotclient buiild is outdated 10 Months. Is this still needed?

**Comment by guruz** [comment]
> Testpilotclient buiild is outdated 10 Months. Is this still needed?

Ideally we'd have testpilot and owncloud builds linked from owncloud.org/download
Feel free to fix.
(And not only during beta/rc phases)

**Comment by jnweiger** [comment]
There are two projects for testpilotcloud-client: 
* isv:ownCloud:testpilot:nightly   is filled in by rotor every night, but broken: had no build targets and no dependencies.
* isv:ownCloud:community:nightly  was last upated 10 months ago, outdated set of build targets.

Fixed:
* isv:ownCloud:community:nightly now links to isv:ownCloud:testpilot:nightly -- why did we have two?
* build targets added, dependencies fixed.

Now testpilotcloud-client is build nightly in both projects. Still with old QT libs.

**Comment by guruz** [comment]
@michaelstingl @jnweiger @dschmidt So the plan for the upcoming 2.3.2 is 
1) To go as usual with old distro Qt packages (and provide 5.6.2 based a bit later)
2) to provide download links for both our old packages with distro Qt and for new packages with 5.6.2
 3) To provide only 5.6.2 based packages

I'd guess we still go for 1) as this is the least work and danger of breaking things?

**Comment by michaelstingl** [comment]
I will provide status with @jnweiger and @dschmidt later today. From what I know today, I would vote for **1)**.

**Comment by hodyroff** [comment]
3) I would really like to understand what needs to happen to make this possible.

**Comment by michaelstingl** [comment]
This are the next steps as discussed today with @dschmidt and @jnweiger :

1. @jnweiger replaces genbranding.pl with [3 new scripts](https://github.com/owncloud/administration/tree/master/jenkins/obs_integration/genbranding)
2. @dschmidt creates new branding templates with new scheme
3. @jnweiger builds an example branding manually to test-drive ( @SamuAlfageme It would be cool to have installation and execution tested on all distros )
4. @jnweiger Will clone the existing Jenkins job and and adjust for the modified process
5. @SamuAlfageme can then test the new auto-build branded clients on all distros

As soon we have a branded testpilotcloud client with 5.6.2, we can involve a bigger audience.  Internal qa continues Tuesday.

**Comment by guruz** [comment]
> guruz modified the milestone: 2.3.3 (Qt 5.6.2 for Linux), 2.3.2 just now

FYI

**Comment by jnweiger** [comment]
https://build.opensuse.org/project/show/isv:ownCloud:devel:Qt562 is still at 2.3.1 :-(

**Comment by jnweiger** [comment]
4). Done. We now have ownCloud-client-linux-qt562 'cloned' from ownCloud-client-linux in rotor.
This successfully built a nightly tonight:

* https://software.opensuse.org//download.html?project=isv%3AownCloud%3Atestpilot%3Anightly&package=testpilotcloud-client

Please be aware that this pulls in QT packages provided by owncloud. These packages are recognized by a prefix ocqt562-* and the installation procedure looks like this on Ubuntu:

<pre>
$ sudo apt-get install testpilotcloud-client
The following additional packages will be installed:
  libtestpilotcloudsync0 ocqt562-libqt5core5a ocqt562-libqt5dbus5
  ocqt562-libqt5gui5 ocqt562-libqt5keychain1 ocqt562-libqt5network5
  ocqt562-libqt5opengl5 ocqt562-libqt5printsupport5 ocqt562-libqt5sql5
  ocqt562-libqt5sql5-sqlite ocqt562-libqt5webkit5 ocqt562-libqt5widgets5
  ocqt562-libqt5xml5
Suggested packages:
  ocqt562-libqt5libqgtk2
Recommended packages:
  ocqt562-libqt5svg5
The following NEW packages will be installed:
  ocqt562-libqt5core5a ocqt562-libqt5dbus5 ocqt562-libqt5gui5
  ocqt562-libqt5keychain1 ocqt562-libqt5network5 ocqt562-libqt5opengl5
  ocqt562-libqt5printsupport5 ocqt562-libqt5sql5 ocqt562-libqt5sql5-sqlite
  ocqt562-libqt5webkit5 ocqt562-libqt5widgets5 ocqt562-libqt5xml5
The following packages will be upgraded:
  libtestpilotcloudsync0 testpilotcloud-client
2 upgraded, 12 newly installed, 0 to remove and 38 not upgraded.
Need to get 17.9 MB of archives.
After this operation, 63.5 MB of additional disk space will be used.
</pre>

The 17MB download should only happen once and remain in the system under /opt/ownCloud/qt-5.6.2/lib so that there are no collisions with system-provided libraries.

I'd like to collect feedback about this setup. If it works fine for everybody, this should become the layout for all future Linux client releases.

@guruz @SamuAlfageme 

![testpilot-233git-nightly-562](https://cloud.githubusercontent.com/assets/1108546/26104260/4d8fa374-3a3d-11e7-8193-e70cfebdb1d5.png)

Happy syncing....

**Comment by dcialdella** [comment]
I tried to install with this

cd /etc/yum.repos.d/
wget http://download.opensuse.org/repositories/isv:ownCloud:community:nightly/CentOS_7/isv:ownCloud:community:nightly.repo
yum install owncloud-client





Transaction Summary
================================================================================
Install             ( 13 Dependent packages)
Upgrade  1 Package

Total download size: 20 M
Is this ok [y/d/N]: Y
Downloading packages:
No Presto metadata available for isv_ownCloud_community_nightly
(1/14): ocqt562-libQt5Concurrent5-5.6.2-7.1.x86_64.rpm     |  91 kB   00:00     
(2/14): libowncloudsync0-2.4.0~git-3.1.x86_64.rpm          | 438 kB   00:00     
(3/14): ocqt562-libQt5Core5-5.6.2-7.1.x86_64.rpm           | 1.9 MB   00:00     
(4/14): ocqt562-libQt5DBus5-5.6.2-7.1.x86_64.rpm           | 267 kB   00:00     
(5/14): ocqt562-libQt5Network5-5.6.2-7.1.x86_64.rpm        | 693 kB   00:00     
(6/14): ocqt562-libQt5Gui5-5.6.2-7.1.x86_64.rpm            | 2.6 MB   00:00     
(7/14): ocqt562-libQt5PrintSupport5-5.6.2-7.1.x86_64.rpm   | 248 kB   00:00     
(8/14): ocqt562-libQt5Sql5-5.6.2-7.1.x86_64.rpm            | 176 kB   00:00     
(9/14): ocqt562-libQt5Xml5-5.6.2-7.1.x86_64.rpm            | 162 kB   00:00     
(10/14): ocqt562-libQt5Widgets5-5.6.2-7.1.x86_64.rpm       | 2.4 MB   00:00     
(11/14): ocqt562-qt5keychain1-0.7.0-1.4.x86_64.rpm         |  56 kB   00:00     
(12/14): owncloud-client-2.4.0~git-3.1.x86_64.rpm          | 922 kB   00:00     
(13/14): owncloud-client-l10n-2.4.0~git-3.1.x86_64.rpm     | 399 kB   00:00     
(14/14): ocqt562-libqt5-qtwebkit-5.6.2-5.1.x86_64.rpm      | 9.2 MB   00:03     
--------------------------------------------------------------------------------
Total                                              3.2 MB/s |  20 MB  00:06     
Running transaction check
Running transaction test


Transaction check error:
  file /etc/ownCloud/sync-exclude.lst from install of owncloud-client-2.4.0~git-3.1.x86_64 conflicts with file from package owncloud-client-libs-2.3.2-3.el7.x86_64

Error Summary
-------------

**Comment by tessus** [comment]
I am a bit confused. I though that http2 support is only available in QT 5.9, yet the client is still using 5.6 and this ticket is about making 5.6 available across the board.

Shouldn't there be an effort to use QT 5.9 instead?

**Comment by jturcotte** [comment]
@tessus Those things take time and have to be done at the right time during the release cycle. The current plan is to use Qt 5.6 with the ownCloud client 2.3 and 2.4, and use Qt 5.9 starting with 2.5.

**Comment by ogoffart** [comment]
(And that's only for owncloud's official package. The client should work fine with Qt 5.9 if you desire to compile the client yourself and benefit from HTTP/2.  Actually testers are welcome. See instructions in https://doc.owncloud.org/desktop/2.3/building.html )

**Comment by tessus** [comment]
@jturcotte 
> Those things take time and have to be done at the right time during the release cycle. 

Why? I mean this is a client we are talking about, not API breaking server code. Or are there any BC breaking changes in the code for QT? I seriously doubt it.

> The current plan is to use Qt 5.6 with the ownCloud client 2.3 and 2.4, and use Qt 5.9 starting with 2.5.

This is hilarious and I truly hope you are joking. The first time http2 was mentioned in a ticket was April 2015. 2.3 is not even out yet and you are talkig about 2.5? Timeline? Like 2 years from now? So 4 years to make a client use http2.

@ogoffart 

> The client should work fine with Qt 5.9 if you desire to compile the client yourself and benefit from HTTP/2. Actually testers are welcome.

I'd love to. However, several sources mentioned that 200 GB free space is required to compile QT and the client. Hmm, I do have a 250GB SSD in my MacBook with about 40 GB available. Thus compiling it myself is rather out of the question. Otherwise I would have done that when the http2 fix was available. You guys have build machines. Creating such a build shouldn't take longer than a few minutes.

If the client should work fine with QT 5.9, why don't you build it with QT 5.9? If you don't want to use it in releases yet (for whatever reason), call it `{CURRENT_VERSION}-h2` (e.g. 2.3.2-h2)  and make it available to the public. I'm sure you get a lot of testers this way. Most admins really want to get rid of http/1.1. By the time you switch to QT 5.9, QT 6 is probably out.

**Comment by guruz** [comment]
@tessus It's easier than you think and you only need a lot of free space if you compile Qt.
You can instead get a compiled Qt via homebrew: homebrew also has binaries since some time.
https://doc.owncloud.org/desktop/2.3/building.html#mac-os-x

But let's have build support on https://central.owncloud.org/ and not here.

About the 2.5 release: We're aiming for before christmas.

**Comment by michaelstingl** [comment]
@tessus @guruz I opened https://github.com/owncloud/client/issues/5932 for Qt 5.9

**Comment by tessus** [comment]
@guruz I'm using MacPorts and do not want to install Homebrew as well. I believe you that it is easy to compile and I don't doubt that I can do it, but I just don't have the space. I can try using a macports QT binary instead. as I said, I believe that it should be fairly easy for you guys to kick of a build with 5.9. and if you want testers, this is the way to go. you can't expect the average Joe to compile this themselves.
I usually do (but I am a developer myself), but with the current space constraints on my part, it is just not possible (unless I use a QT binary).

thanks @michaelstingl, I've subscribed to #5932 and I hope somebody is able to provide a binary with QT 5.9.

**Comment by guruz** [comment]
2.3.3rc1 builds in https://download.owncloud.com/desktop/testing/ and https://software.opensuse.org//download.html?project=isv%3AownCloud%3Acommunity%3Atesting&package=owncloud-client

**Comment by guruz** [comment]
We're releasing 2.3.3 this week .. if you have issues with Qt 5.6.2 on Linux when using rc1 now is the last chance to speak up ;-)

**Comment by PVince81** [comment]
yep: https://github.com/owncloud/client/issues/5960

**Comment by PVince81** [comment]
Leap 42.3 (not my system) seems to come with Qt 5.6.2 already, so no need to re-bundle it there with the package. It is likely that Tumbleweed also doesn't need this extra bundling.

The bug in question is with Leap 42.2 (the previous version)

**Comment by sgparry** [comment]
Just did regular apt-get on Kubuntu 16.04.03 and owncloud client was de-installed:

``
The following packages have unmet dependencies.
 owncloud-client : Depends: ocqt562-libqt5webkit5 but it is not going to be installed
``

and:

``
sudo apt-get install ocqt562-libqt5webkit5
``

gives:

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 ocqt562-libqt5webkit5 : Depends: ocqt562-libqt5opengl5 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

Help? please?

**Comment by Trebacz** [comment]
My owncloud client seems to be crashing with this message after an update of qt in Ubuntu 17.10 today. Now I can't launch the client and get the message:

owncloud: relocation error: /opt/ownCloud/qt-5.6.2/lib/x86_64-linux-gnu/libQt5OpenGL.so.5: symbol _ZTV26QOpenGLSharedResourceGuard, version Qt_5_PRIVATE_API not defined in file libQt5Gui.so.5 with link time reference

I also filed an issue here:
[(https://central.owncloud.org/t/owncloud-client-fails-to-launch-after-qt-ubuntu-17-10-update-today/9464)]

**Comment by Phlos** [comment]
Hi!
I'm glad others seem to be having similar issues. I tried installing owncloud-client yesterday on my relatively fresh 16.04, and got a whole bunch of weird errors. Trying today again, weird errors, but different ones. Here's what I did:

Yesterday (Thu 14 Sept 2017):
```
$ sudo apt-get install owncloud-client
[sudo] password for phlos: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libowncloudsync0 libxcb-xinerama0 mesa-utils ocqt562-libqt5core5a
  ocqt562-libqt5dbus5 ocqt562-libqt5gui5 ocqt562-libqt5keychain1
  ocqt562-libqt5network5 ocqt562-libqt5opengl5 ocqt562-libqt5printsupport5
  ocqt562-libqt5sql5 ocqt562-libqt5sql5-sqlite ocqt562-libqt5webkit5
  ocqt562-libqt5widgets5 ocqt562-libqt5xml5 owncloud-client-l10n
Suggested packages:
  ocqt562-libqt5libqgtk2 owncloud-client-dolphin owncloud-client-nautilus
  owncloud-client-nemo owncloud-client-caja
Recommended packages:
  ocqt562-libqt5svg5
The following NEW packages will be installed:
  libowncloudsync0 libxcb-xinerama0 mesa-utils ocqt562-libqt5core5a
  ocqt562-libqt5dbus5 ocqt562-libqt5gui5 ocqt562-libqt5keychain1
  ocqt562-libqt5network5 ocqt562-libqt5opengl5 ocqt562-libqt5printsupport5
  ocqt562-libqt5sql5 ocqt562-libqt5sql5-sqlite ocqt562-libqt5webkit5
  ocqt562-libqt5widgets5 ocqt562-libqt5xml5 owncloud-client
  owncloud-client-l10n
0 upgraded, 17 newly installed, 0 to remove and 105 not upgraded.
Need to get 18,5 MB/18,5 MB of archives.
After this operation, 70,2 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
Err:1 https://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04  ocqt562-libqt5core5a 5.6.2-1+14.1
  Protocol "http" not supported or disabled in libcurl
Err:2 https://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04  ocqt562-libqt5dbus5 5.6.2-1+14.1
  Protocol "http" not supported or disabled in libcurl
Err:3 https://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04  ocqt562-libqt5network5 5.6.2-1+14.1
  Protocol "http" not supported or disabled in libcurl
Err:4 https://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04  ocqt562-libqt5gui5 5.6.2-1+14.1
  Protocol "http" not supported or disabled in libcurl
Err:5 https://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04  ocqt562-libqt5widgets5 5.6.2-1+14.1
  Protocol "http" not supported or disabled in libcurl
Err:6 https://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04  ocqt562-libqt5opengl5 5.6.2-1+14.1
  Protocol "http" not supported or disabled in libcurl
Err:7 https://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04  ocqt562-libqt5printsupport5 5.6.2-1+14.1
  Protocol "http" not supported or disabled in libcurl
Err:8 https://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04  ocqt562-libqt5sql5 5.6.2-1+14.1
  Protocol "http" not supported or disabled in libcurl
Err:9 https://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04  ocqt562-libqt5webkit5 5.6.2-1
  Protocol "http" not supported or disabled in libcurl
Err:10 https://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04  ocqt562-libqt5keychain1 0.7.0-1+4.2
  Protocol "http" not supported or disabled in libcurl
Err:11 https://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04  libowncloudsync0 2.3.3-8338
  Protocol "http" not supported or disabled in libcurl
Err:12 https://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04  ocqt562-libqt5sql5-sqlite 5.6.2-1+14.1
  Protocol "http" not supported or disabled in libcurl
Err:13 https://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04  ocqt562-libqt5xml5 5.6.2-1+14.1
  Protocol "http" not supported or disabled in libcurl
Err:14 https://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04  owncloud-client-l10n 2.3.3-8338
  Protocol "http" not supported or disabled in libcurl
Err:15 https://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04  owncloud-client 2.3.3-8338
  Protocol "http" not supported or disabled in libcurl
```

Was rather confused by this since as far as I can see, curl has a http protocol. 
After this, I gave up yesterday.

Today (15 Sept 2017), new try:
```
$ sudo apt-get install owncloud-client
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 owncloud-client : Depends: ocqt562-libqt5webkit5 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

I did some attempts with `sudo apt-get update`, `sudo apt-get autoremove`, separately installing `ocqt562-libqt5webkit5` and `ocqt562-libqt5opengl5` manually but the latter gives
```
$ sudo apt-get install ocqt562-libqt5opengl5
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package ocqt562-libqt5opengl5 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ocqt562-libqt5opengl5' has no installation candidate
```
which is ultimately how I ended up here. So the problem seems to be centering on `ocqt562-libqt5opengl5` -- but here all my wisdom stops. 

Ideas? Help?

**Comment by bytepan** [comment]
Same issue -- please fix it ASAP.
Thanks !

**Comment by kjakobs** [comment]
Had the same problem and found solution here: [link](https://forums.linuxmint.com/viewtopic.php?f=47&t=253795)
In short words:
-comment out the source entry for opensuse repository under /etc/apt/sources.list.d/[your owncloud repo].list
-`apt-get update`
-`apt-get install owncloud-client`

**Comment by SamuAlfageme** [comment]
@kjakobs commenting out those line installs a really old client version from your distribution's mirror. I'd suggest you to try the link in https://github.com/owncloud/client/issues/6034#issuecomment-329740446 while we try to fix the dependencies issue.

**Comment by jnweiger** [comment]
The ocqt562-libqt5opengl5 package disappeared last night. I'll bring it back.

**Comment by Phlos** [comment]
The alternative mirror suggested by @SamuAlfageme in #6034 works for me to get the installation working. Thanks!

**Comment by moscicki** [comment]
A side note: why do you need opengl for the sync client??

**Comment by jnweiger** [comment]
the normal install from https://software.opensuse.org//download.html?project=isv%3AownCloud%3Adesktop&package=owncloud-client
now also works again as it should, including ocqt562-libqt5opengl5. Sorry for the inconvenience!

**Comment by TimTim2017** [comment]
Just tried it with my Linux Mint 18.2 system  and still get the same error. I installed a fresh Ubuntu 16.04 in Virtual Box and also get the same error.

**Comment by jnweiger** [comment]
@moscicki opengl is completely useless here. But the opengl dependency propagates from qtbase to the client. I cannot change that without re-releasing everything. 
Next release of the client will be built against a qt that has opengl disabled. That should help to reduce the dependency footprint.

**Comment by millivenn** [comment]
I tried to switch to the alternative repository as suggested by @SamuAlfageme in #6034
I still get a relocation error in Ubtuntu 14.04

**Comment by csgroen** [comment]
I just installed using the alternative repository. The installation went well, but I'm getting the relocation error as well (Debian 9).

`owncloud: relocation error: /opt/ownCloud/qt-5.6.2/lib/x86_64-linux-gnu/libQt5OpenGL.so.5: symbol _ZTV26QOpenGLSharedResourceGuard, version Qt_5_PRIVATE_API not defined in file libQt5Gui.so.5 with link time reference`

**Comment by guruz** [comment]
Sorry for the messups with the Qt compile. We hope it works now for everyone in the current 2.3.3 packages.
