### ISSUE TITLE
Build OwnCloud windows client failed to linking with Qt

### ISSUE THREAD

**Issue by hungnvz** [owncloud/client#5771]
Hi !
I have a problem when tried to build ownCloud on Windows using MingW.
I followed the tutorial at: https://github.com/owncloud/client/blob/master/doc/building.rst but not lucky.
I faced error in step 7.
OpenSSL, qtkeychain, Qt, Mingw have set in PATH.
This is my CMake configure:
![1](https://cloud.githubusercontent.com/assets/19268064/26047522/b5d28c8c-397d-11e7-84a9-dc6264c7221e.jpg)

Building CXX object is OK:
![2](https://cloud.githubusercontent.com/assets/19268064/26047524/b9d21906-397d-11e7-8240-50bdf4994095.jpg)

But error when linking to necessary Qt object:
![3](https://cloud.githubusercontent.com/assets/19268064/26047578/f5a6445c-397d-11e7-85d1-33899a9f8554.jpg)

I guest it not found Qt library in path. 
Please help me to solve problem. Thanks everyone !

**Comment by SamuAlfageme** [comment]
Hey @hungnvz! Did you also followed the generic build instructions: https://doc.owncloud.org/desktop/2.3/building.html#generic-build-instructions, particularly the ones that say:

> To build the most up-to-date version of the client:
>        1. Clone the latest versions of the client from Git as follows:

```
git clone git://github.com/owncloud/client.git
cd client
git submodule init
git submodule update
```

I've just noticed the "Windows Development Build" instructions are not very clear about this particular step. (We know: https://github.com/owncloud/client/issues/5739 and should be fixed in the near future).

Also, copy-paste here the whole build error trace, since the screenshot misses some parts that could be important. Thanks!

**Comment by guruz** [comment]
The place for help on building is https://central.owncloud.org/ therefore I close the issue here.

However you can still continue to ask on the issue here and we try to help you. :)

**Comment by guruz** [comment]
Can you compile minimal Qt examples?
