### ISSUE TITLE
Upload fails with "Error writing metadata to the database" when using VFS

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#8754]
On Windows with a sync running VFS, a user relatively often sees the error message _"Error writing metadata to the database"_ when uploading files from the local machine.

It turns out that in the `updateMetadata()` method, which is actually triggering the error message, returns false in two cases: 
1. If the sync journal file record can not be written for whatever reason.
2. If the `vfs.convertToPlaceholder()` method returns false. 

The latter looks like the source of the problem. The suspicion is that the call to `CfOpenFileWithOplock` in `convertToPlaceholder` fails because the target file is locked, for example by an external app or because it is just in use.

The client must be able to deal with that situation as it can not be avoided.

Also see a related post here:

https://central.owncloud.org/t/windows-2-7-6-error-writing-metadata-when-using-virtual-files-ubuntu-server/31888/3

**Comment by TheOneRing** [comment]
Fixed in 2.9

**Comment by MichaKersloot** [comment]
Hi,

I've got a question on this. Is this change only for virtual files? As we now seem to have files that are not syncing when op by the application and we are not using virtual files.

**Comment by TheOneRing** [comment]
The described error only occurred with windows virtual files.
However 2.9 also improved the handling of locked files on Windows.

**Comment by michaelstingl** [comment]
> As we now seem to have files that are not syncing when op by the application and we are not using virtual files.

@MichaKersloot please check again with latest daily builds:

- https://download.owncloud.com/desktop/ownCloud/daily/2.9/win/?sort=time&order=desc
- https://download.owncloud.com/desktop/ownCloud/daily/2.9/mac/?sort=time&order=desc
- https://download.owncloud.com/desktop/ownCloud/daily/2.9/linux/download/

In case you still experience problems, please open new issue and provide the required information.
