### ISSUE TITLE
owncloud --version reports `Using virtual files plugin: off`

### ISSUE THREAD

**Issue by JoKalliauer** [owncloud/client#9155]
### Expected behaviour
`owncloud --version` should report `Using virtual files plugin: suffix`

### Actual behaviour
`owncloud --version` reports `Using virtual files plugin: off`

### Steps to reproduce
1. `owncloud --version`

### Screenshot
![Screenshot from 2021-10-15 15-43-13](https://user-images.githubusercontent.com/15687581/137497185-bedadf4b-071a-435a-8ee9-66d2472c2314.png)

### Server configuration
Web server: https://owncloud.tuwien.ac.at

ownCloud version: https://owncloud.tuwien.ac.at/status.php

| name | value |
|  -- | -- |
|installed | true|
|maintenance | false|
|needsDbUpgrade | false|
|version | "10.7.0.4"|
|versionstring | "10.7.0"|
|edition | "Enterprise"|<
|productname | "ownCloud TU Wien"|

### Client configuration
Client version: `owncloud --version`
```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
ownCloud ownCloud 2.9.1 (build 5500) Oct 13 2021 08:34:12
https://github.com/owncloud/client/commit/42fb299cadd56dc5b7f99bb6946f5bed8a53a2eb
Libraries Qt 5.12.10, OpenSSL 1.1.1l  FIPS 24 Aug 2021
Using virtual files plugin: off
fedora-5.14.11-200.fc34.x86_64
```

Operating system: `$ hostnamectl`
```
 Static hostname: lws84.imws.tuwien.ac.at
       Icon name: computer-laptop
         Chassis: laptop
      Machine ID: 96434f58f7644401a3f9d69da903899d
         Boot ID: ce0b799699ae4148ae05550cf1937bb7
Operating System: Fedora 34 (Workstation Edition) 
     CPE OS Name: cpe:/o:fedoraproject:fedora:34
          Kernel: Linux 5.13.15-200.fc34.x86_64
    Architecture: x86-64
 Hardware Vendor: Lenovo
```

OS language:  `$ locale`
```
LANG=en_GB.UTF-8
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC=de_AT.UTF-8
LC_TIME=de_AT.UTF-8
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY=de_AT.UTF-8
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER=de_AT.UTF-8
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT=de_AT.UTF-8
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=
```

Qt version used by client package (Linux only, see also Settings dialog):
```
ownCloud 2.9.1 (build 5500) 42fb29 Oct 13 2021 08:34:12
Libraries Qt 5.12.10, OpenSSL 1.1.1l FIPS 24 Aug 2021
Using virtual files plugin: suffix
fedora-5.14.11-200.fc34.x86_64
```

Client package (From ownCloud or distro) (Linux only): `$ dnf list owncloud*`
```
Installed Packages
owncloud-client.x86_64                   2.9.1-5500   @owncloud
owncloud-client-nautilus.x86_64          2.9.1-5500   @owncloud
owncloud-client-nemo.x86_64              2.9.1-5500   @owncloud
owncloud-client-overlays-icons.x86_64    2.9.1-5500   @owncloud
```

Installation path of client:
`/opt/ownCloud/ownCloud/bin/owncloud`

### Logs
see https://github.com/owncloud/client/issues/9052#issuecomment-922250501

**Comment by michaelstingl** [comment]
Related? https://github.com/owncloud/client/issues/8174 (was fixed in 2.7)

Regression?

**Comment by TheOneRing** [comment]
We had the issue before and the issue used to be that we printed the about text before we loaded the plugins...

**Comment by TheOneRing** [comment]
Also https://github.com/owncloud/client/blob/a286529b46de1fd7f2e19c59ec719be4f8961ca8/src/gui/application.cpp#L279-L280 for or package manager based installs.

**Comment by erikjv** [comment]
lgtm

**Comment by gabi18** [comment]
Issue still seen with client 2.10.1-rc1 on openSUSE 15.3

![suffix-off](https://user-images.githubusercontent.com/75983861/159224657-3f89e523-37af-4e7a-bba5-5ef5eec9eca2.png)

**Comment by gabi18** [comment]
Confirmed fixed in RC2

![version-suffix](https://user-images.githubusercontent.com/75983861/160360296-c9f2e563-d39c-4ade-ba61-e67a8913130f.png)

**Comment by JoKalliauer** [comment]
As the reporter I also confirm that it is fixed:
```bash
ownCloud ownCloud 2.10.1 (build 7187) Apr  5 2022 11:11:57
https://github.com/owncloud/client/commit/82eefdafa2ec7a1927df87c850d9e6f1e9dac6af
Libraries Qt 5.12.10, OpenSSL 1.1.1n  FIPS 15 Mar 2022
Using virtual files plugin: suffix
fedora-5.17.1-300.fc36.x86_64
```
